### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by onfootbug** [proxysu/ProxySU#106]
大佬你好，三个月前我用ProxySU在搬瓦工上装了trojan，客户端用的是v2rayN,这段时间一直用的好好的， 今天突然就连不上了，提示：x509: certificate has expired or is not yet valid，想问一下证书应该是会隔段时间自动申请的吧？这种情况我该怎么排查问题呢？先谢谢了！

**Comment by hunsx** [comment]
同样出现这个问题，准点3个月证书失效，需要重新卸载安装trojan

**Comment by next-autumn** [comment]
acme.sh的申请证书脚本，上次改策略了，需要邮箱才能申请，重装吧。

**Comment by next-autumn** [comment]
Duplicate of #110
