### ISSUE TITLE
实测证书并不能自动更新。

### ISSUE THREAD

**Issue by nethawkhu** [proxysu/ProxySU#110]
安装时候使用的是 Xray 中的尝鲜方案 Vless + Vmess + Torjan +Xtls 。

证书完全不会自动更新，时间到了证书就过期了。

**Comment by next-autumn** [comment]
新版在测试中，会修复这个问题。
感谢。

**Comment by next-autumn** [comment]
有些些VPS 没有默认安装crontab，执行计划任务失败。
随后修复 + 主动续签功能
