### ISSUE TITLE
xray启动失败(第二次)！退出安装！

### ISSUE THREAD

**Issue by qian9008** [proxysu/ProxySU#112]
xray启动失败(第二次)！退出安装！
journalctl -n50 --no-pager --boot -u  xray
-- Logs begin at Wed 2021-03-03 05:35:18 HKT, end at Wed 2021-03-03 10:56:10 HKT. --
Mar 03 10:56:03 VM-0-9-debian systemd[1]: Started Xray Service.
Mar 03 10:56:03 VM-0-9-debian xray[27884]: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
Mar 03 10:56:03 VM-0-9-debian xray[27884]: A unified platform for anti-censorship.
Mar 03 10:56:03 VM-0-9-debian xray[27884]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /usr/local/bin/geoip.dat: no such file or directory
Mar 03 10:56:03 VM-0-9-debian systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Mar 03 10:56:03 VM-0-9-debian systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 03 10:56:10 VM-0-9-debian systemd[1]: Started Xray Service.
Mar 03 10:56:10 VM-0-9-debian xray[27899]: Xray 1.3.0 (Xray, Penetrates Everything.) Custom (go1.15.8 linux/amd64)
Mar 03 10:56:10 VM-0-9-debian xray[27899]: A unified platform for anti-censorship.
Mar 03 10:56:10 VM-0-9-debian xray[27899]: Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /usr/local/bin/geoip.dat: no such file or directory
Mar 03 10:56:10 VM-0-9-debian systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Mar 03 10:56:10 VM-0-9-debian systemd[1]: xray.service: Failed with result 'exit-code'.

xray启动失败，原因如上！请排查原因！
发生错误，安装中断......

**Comment by next-autumn** [comment]
是debian 9的系统吗？
