### ISSUE TITLE
caddy永远启动失败，安装终止

### ISSUE THREAD

**Issue by wai3886** [proxysu/ProxySU#113]

**Comment by wai3886** [comment]
caddy启动失败！
正在第二次尝试启动caddy
systemctl restart caddy

ps aux | grep caddy
root      2616  0.0  0.6  11592  3128 ?        Ss   13:26   0:00 bash -c ps aux | grep caddy
root      2618  0.0  0.2  13136  1032 ?        S    13:26   0:00 grep caddy

caddy启动失败(第二次)！退出安装！
journalctl -n50 --no-pager --boot -u  caddy
-- Logs begin at Sun 2021-03-07 13:19:53 EST, end at Sun 2021-03-07 13:26:53 EST. --
Mar 07 13:26:45 localhost.localdomain caddy[2600]: runtime.Compiler=gc
Mar 07 13:26:45 localhost.localdomain caddy[2600]: runtime.NumCPU=1
Mar 07 13:26:45 localhost.localdomain caddy[2600]: runtime.GOMAXPROCS=1
Mar 07 13:26:45 localhost.localdomain caddy[2600]: runtime.Version=go1.15.6
Mar 07 13:26:45 localhost.localdomain caddy[2600]: os.Getwd=/
Mar 07 13:26:45 localhost.localdomain caddy[2600]: LANG=en_US.UTF-8
Mar 07 13:26:45 localhost.localdomain caddy[2600]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Mar 07 13:26:45 localhost.localdomain caddy[2600]: HOME=/root
Mar 07 13:26:45 localhost.localdomain caddy[2600]: LOGNAME=root
Mar 07 13:26:45 localhost.localdomain caddy[2600]: USER=root
Mar 07 13:26:45 localhost.localdomain caddy[2600]: SHELL=/bin/sh
Mar 07 13:26:45 localhost.localdomain caddy[2600]: INVOCATION_ID=85e5201c8e7e440f9f736d6785e60374
Mar 07 13:26:45 localhost.localdomain caddy[2600]: JOURNAL_STREAM=9:26492
Mar 07 13:26:45 localhost.localdomain caddy[2600]: {"level":"info","ts":1615141605.3855698,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Mar 07 13:26:45 localhost.localdomain caddy[2600]: {"level":"info","ts":1615141605.3885572,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
Mar 07 13:26:45 localhost.localdomain caddy[2600]: {"level":"info","ts":1615141605.3889887,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
Mar 07 13:26:45 localhost.localdomain caddy[2600]: {"level":"info","ts":1615141605.3897424,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000225b90"}
Mar 07 13:26:45 localhost.localdomain caddy[2600]: {"level":"info","ts":1615141605.389982,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000225b90"}
Mar 07 13:26:45 localhost.localdomain caddy[2600]: run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 1: loading matcher modules: module name 'path': module value cannot be null
Mar 07 13:26:45 localhost.localdomain systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 13:26:45 localhost.localdomain systemd[1]: caddy.service: Failed with result 'exit-code'.
Mar 07 13:26:53 localhost.localdomain systemd[1]: Started Caddy.
Mar 07 13:26:53 localhost.localdomain caddy[2610]: caddy.HomeDir=/root
Mar 07 13:26:53 localhost.localdomain caddy[2610]: caddy.AppDataDir=/root/.local/share/caddy
Mar 07 13:26:53 localhost.localdomain caddy[2610]: caddy.AppConfigDir=/root/.config/caddy
Mar 07 13:26:53 localhost.localdomain caddy[2610]: caddy.ConfigAutosavePath=/root/.config/caddy/autosave.json
Mar 07 13:26:53 localhost.localdomain caddy[2610]: caddy.Version=v2.3.0
Mar 07 13:26:53 localhost.localdomain caddy[2610]: runtime.GOOS=linux
Mar 07 13:26:53 localhost.localdomain caddy[2610]: runtime.GOARCH=amd64
Mar 07 13:26:53 localhost.localdomain caddy[2610]: runtime.Compiler=gc
Mar 07 13:26:53 localhost.localdomain caddy[2610]: runtime.NumCPU=1
Mar 07 13:26:53 localhost.localdomain caddy[2610]: runtime.GOMAXPROCS=1
Mar 07 13:26:53 localhost.localdomain caddy[2610]: runtime.Version=go1.15.6
Mar 07 13:26:53 localhost.localdomain caddy[2610]: os.Getwd=/
Mar 07 13:26:53 localhost.localdomain caddy[2610]: LANG=en_US.UTF-8
Mar 07 13:26:53 localhost.localdomain caddy[2610]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Mar 07 13:26:53 localhost.localdomain caddy[2610]: HOME=/root
Mar 07 13:26:53 localhost.localdomain caddy[2610]: LOGNAME=root
Mar 07 13:26:53 localhost.localdomain caddy[2610]: USER=root
Mar 07 13:26:53 localhost.localdomain caddy[2610]: SHELL=/bin/sh
Mar 07 13:26:53 localhost.localdomain caddy[2610]: INVOCATION_ID=12808d9f196c49e4bb9f2c99dd4d2827
Mar 07 13:26:53 localhost.localdomain caddy[2610]: JOURNAL_STREAM=9:26700
Mar 07 13:26:53 localhost.localdomain caddy[2610]: {"level":"info","ts":1615141613.329912,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Mar 07 13:26:53 localhost.localdomain caddy[2610]: {"level":"info","ts":1615141613.3321075,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
Mar 07 13:26:53 localhost.localdomain caddy[2610]: {"level":"info","ts":1615141613.332449,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
Mar 07 13:26:53 localhost.localdomain caddy[2610]: {"level":"info","ts":1615141613.332833,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001fd2d0"}
Mar 07 13:26:53 localhost.localdomain caddy[2610]: {"level":"info","ts":1615141613.3330183,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc0001fd2d0"}
Mar 07 13:26:53 localhost.localdomain caddy[2610]: run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 1: loading matcher modules: module name 'path': module value cannot be null
Mar 07 13:26:53 localhost.localdomain systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 07 13:26:53 localhost.localdomain systemd[1]: caddy.service: Failed with result 'exit-code'.

caddy启动失败，原因如上！请排查原因！
发生错误，安装中断......

**Comment by messiLiao** [comment]
你用 systemctl status caddy看一下，会有错误信息的

**Comment by next-autumn** [comment]
4.0.1解决了一些caddy不兼容问题。
