### ISSUE TITLE
证书无法自动更新

### ISSUE THREAD

**Issue by kobehuanghai** [proxysu/ProxySU#114]
去年底通过proxysu搭建了两台vless+tcp+xtls的服务器，一直运行稳定，先谢谢作者的无私付出和贡献。
但是最近两天突然发现两台服务器的证书都相继过期了导致无法连接，貌似脚本不能自动续期？最后都是通过重新再搭建一次解决，比较麻烦。想问问这是个早期脚本的bug后来已经修复还是说未来也会这样无法解决？如果无法自动续期的话请问如何手动解决？需要自己用命令行解决还是考虑加一个手动续期的功能？再次感谢作者的付出和贡献。

**Comment by next-autumn** [comment]
有些些VPS 没有默认安装crontab，执行计划任务失败，随后修复。
可能还有其他环境的问题，为了避免麻烦随后 + 主动续签功能。
