### ISSUE TITLE
root權限問題

### ISSUE THREAD

**Issue by lowaiting** [proxysu/ProxySU#115]
![783E587B-B210-47EA-9A81-CE55D2987D51](https://user-images.githubusercontent.com/55861765/110669347-3590dc00-8207-11eb-90b1-7e0b2471560f.jpeg)
請教一下，同一服務器，服務器用centos7則一切正常安裝，但服務器轉成centos8則說我沒有root權限？我明明用root登陸的啊。這個可以怎樣解決？

**Comment by next-autumn** [comment]
是哪家的VPS商呢，或者主机是不是禁止root远程登录，这个应该是系统权限问题，google一下吧！

**Comment by lowaiting** [comment]
魔方雲，主機是可以root登陸的，但用proxysu安裝時就出現root權限提示了
