### ISSUE TITLE
只解析ipv6域名的检查问题

### ISSUE THREAD

**Issue by dakkidaze** [proxysu/ProxySU#117]
正在检测域名是否解析到当前VPS的IP上......
dig @resolver1.opendns.com A example.com +short -4 | grep  -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1

域名未能正确解析到当前VPS的IP上!安装失败！
发生错误，安装中断......

脚本只会检查A记录，不检查AAAA记录，如果一台双栈机器，域名只解析了v6，在这一步就会通不过，尽管能够使用该域名通过ipv6达到这台主机，希望有空能修复一下

**Comment by next-autumn** [comment]
mark

**Comment by MisCusi2023** [comment]
新版软件，应该已经解决这个问题，请下载最新版。
