### ISSUE TITLE
功能建议：保留卸载功能

### ISSUE THREAD

**Issue by MFYDev** [proxysu/ProxySU#119]
很感谢ProxySU这款工具让我们自建变得更加简单。

但是更新到 v3.0.1 之后，我注意到了软件本身没有了卸载服务器端 XRay 的选项。

我认为无论如何，卸载功能都是不应该去掉的。毕竟万一服务器如果突然决定另作他用，将导致不得不重装系统，如果可以直接卸载，那将会方便很多。

仅个人建议，希望能把卸载功能保留。

**Comment by next-autumn** [comment]
会保留的，下个版本会把原有功能转移过来。

**Comment by lgfyxx1** [comment]
> 会保留的，下个版本会把原有功能转移过来。

下个版本大约啥时候呀~~~

**Comment by next-autumn** [comment]
fix it. v3.1.0
