### ISSUE TITLE
建议在xtls模板中添加TLS版本的限制

### ISSUE THREAD

**Issue by shoushi01** [proxysu/ProxySU#124]
建议在xtls模板中添加TLS最低版本的限制。如不进行限制，会允许使用TLS1.0等较不安全的tls版本。望开发者予以考虑。

            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "allowInsecure": false,    // 正常使用应确保关闭
                    "minVersion": "1.2",       // TLS最低版本设置
                    "alpn": [
                        "http/1.1"
                    ],
                    "certificates": [
                        {
                            "certificateFile": "/home/vpsadmin/xray_cert/xray.crt",
                            "keyFile": "/home/vpsadmin/xray_cert/xray.key"
                        }
                    ]
                }
            }

**Comment by next-autumn** [comment]
thanks.

**Comment by next-autumn** [comment]
fix it.
