### ISSUE TITLE
3.1版本问题

### ISSUE THREAD

**Issue by simonfxm** [proxysu/ProxySU#129]
3.1的版本里面原先的TROJAN-GO，还有其它的选项怎么都没了，界面也换了，有没有使用教程
用之前的老版本就直接闪退

**Comment by reman-l** [comment]
MTP搭建的选项也没了，最好还是集成上吧，不用再换个脚本装了

**Comment by shoushi01** [comment]
貌似现在是全面xray化，不再使用trojan-go了。不过我倒是有个疑惑：端口自定义在哪里啊？直接修改配置文件的吗？

**Comment by next-autumn** [comment]
自定义端口新版开放了。

xray以外的还请先用旧版本吧，新版的根据建议再考虑下！

**Comment by next-autumn** [comment]
後續版本抽空會陸續添加 trojan-go native等原版上的功能。

**Comment by next-autumn** [comment]
4.0.1  trojan-go  NaiveProxy
