### ISSUE TITLE
Xray 流控选择

### ISSUE THREAD

**Issue by CapSOSkw** [proxysu/ProxySU#138]
你好，是否可以考虑加入流控选择？splice 我在windows的qv2ray上会报错， direct就没问题。

**Comment by winnochan** [comment]
@CapSOSkw  splice只支持Linux系统使用, 因为需要使用Linux特殊的系统API, 所以Windows和Mac都不支持，和这个脚本无关

**Comment by colindog** [comment]
> @CapSOSkw splice只支持Linux系统使用, 因为需要使用Linux特殊的系统API, 所以Windows和Mac都不支持，和这个脚本无关

所以才应该加上选择，支持改为direct，不然用脚本配置了server端，windows客户端就没法使用了

**Comment by next-autumn** [comment]
客户端用direct可以用吧，只是xtls文档里推荐splice性能好，服务器还是用的direct兼容性好。

**Comment by colindog** [comment]
现在默认的配置服务器是splice,所以脚本配置完windows客户端没法用
