### ISSUE TITLE
连续删除安装几次后无法申请证书

### ISSUE THREAD

**Issue by gswangmd-gssi** [proxysu/ProxySU#144]
如何破解？
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

**Comment by gswangmd-gssi** [comment]
换二级域名也不行。

**Comment by next-autumn** [comment]
连续多次申请会被域名商拒绝，试试换域名，还不行
请到 https://github.com/acmesh-official/acme.sh 提问。
