### ISSUE TITLE
安装成功，电脑连接错误问题

### ISSUE THREAD

**Issue by wox-x** [proxysu/ProxySU#146]
系统版本：Debian10
软件版本：ProxySU 3.1.3
V2rayN版本：4.15
内核v2fly版本 4.38.3
内核xray版本 1.4.2
安装使用环境全是最新版
通过ProxySU成功安装第一个推荐XTLS，网站模板也上传成功，可以访问网页
但是，把配置信息添加到电脑v2rayN后，服务器PING有300多延迟
测试真连接延迟，提示：基础连接已经关闭，发送时发生错误
测试服务器速度，提示：远程服务器返回错误503，服务器不可以
怎么解决啊？
手机端使用v2rayNG连接没有任何问题，可以正常使用。

**Comment by next-autumn** [comment]
手机能连上说明安装是正常的，请到群里提问。
