### ISSUE TITLE
关于无法手动/自动续签证书解决方案

### ISSUE THREAD

**Issue by edmund-zhao** [proxysu/ProxySU#148]
## 测试平台 Centos7、Debian9、Debian10

- 第一步

linux登录：执行以下命令

`"/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" --force`

会出现以下报错

![image](https://user-images.githubusercontent.com/53864204/120355530-f2da2e00-c335-11eb-8384-1f33f50f66b2.png)

- 查看报错

**很明显是由于80端口被占用，导致无法续签**

- KILL

`kill -9 (填入报错的pidId)`

**Comment by next-autumn** [comment]
4.0.1 解决了这个问题。
在签发证书时候，会自动停止caddy服务器，签发完成自动启动caddy服务器
