### ISSUE TITLE
大佬，安装trojan会报错

### ISSUE THREAD

**Issue by 1665169869** [proxysu/ProxySU#149]
`正在登陆服务器 ...
登陆服务器成功！
sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
if [[ -f /usr/local/bin/trojan-go ]];then echo '1';else echo '0'; fi
1
检测安装系统环境...
command -v apt-get

command -v dnf

command -v yum
/usr/bin/yum
command -v systemctl
/usr/bin/systemctl
command -v getenforce
/usr/sbin/getenforce
getenforce
Disabled
检测安装系统环境完成
配置服务器端口...
lsof -n -P -i :80 | grep LISTEN
caddy     9908 root    8u  IPv6 113496      0t0  TCP *:80 (LISTEN)
安装终止，80端口被占用，安装停止!
systemctl stop trojan-go

systemctl stop caddy

rm -rf caddy_install.sh

curl -o caddy_install.sh https://raw.githubusercontent.com/proxysu/shellscript/master/Caddy-Naive/caddy-naive-install.sh

yes | bash caddy_install.sh uninstall
Shutting down caddy service.
Removed: /etc/systemd/system/caddy.service
Removing caddy binaries & files.
Removed: /usr/bin/caddy
Removed: /etc/caddy
Removed caddy successfully.
rm -rf caddy_install.sh

rm -rf /usr/share/caddy

rm -rf /usr/local/bin/trojan-go

rm -rf /usr/local/etc/trojan-go

acme.sh --uninstall

rm -r  ~/.acme.sh

卸载Trojan-Go完成
sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
if [[ -f /usr/local/bin/trojan-go ]];then echo '1';else echo '0'; fi
0
检测安装系统环境...
command -v systemctl
/usr/bin/systemctl
command -v getenforce
/usr/sbin/getenforce
getenforce
Disabled
检测安装系统环境完成
配置服务器端口...
lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

端口配置完成
安装必要的系统工具...
command -v sudo
/usr/bin/sudo
command -v curl
/usr/bin/curl
command -v wget
/usr/bin/wget
command -v unzip
/usr/bin/unzip
command -v dig
/usr/bin/dig
echo y | yum -y install xz-devel
Loaded plugins: langpacks
Package xz-devel-5.2.2-1.el7.x86_64 already installed and latest version
Nothing to do
command -v lsof
/usr/sbin/lsof
系统工具安装完成
检测IP6...
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
52.175.62.40
检测IP6完成
配置防火墙...
command -v firewall-cmd
/usr/bin/firewall-cmd
firewall-cmd --state
running
firewall-cmd --zone=public --add-port=80/tcp --permanent
success
firewall-cmd --zone=public --add-port=80/udp --permanent
success
firewall-cmd --zone=public --add-port=443/tcp --permanent
success
firewall-cmd --zone=public --add-port=443/udp --permanent
success
yes | firewall-cmd --reload
success
防火墙配置完成
同步系统和本地时间...
rm -f /etc/localtime

ln -s /usr/share/zoneinfo/UTC /etc/localtime

date +%s
1622623643
时间同步完成
检测域名是否绑定本机IP...
dig @resolver1.opendns.com A vps.baiyu.fun +short -4 | grep  -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1
52.175.62.40
域名检测完成
安装Caddy...
rm -rf caddy_install.sh

curl -o caddy_install.sh https://raw.githubusercontent.com/proxysu/shellscript/master/Caddy-Naive/caddy-naive-install.sh

yes | bash caddy_install.sh
Caddy 2 is not installed. start installation
Cretated: /etc/caddy
Archive:  /tmp/caddy.zip
  inflating: /usr/bin/caddy          
Installed: /usr/bin/caddy
Building caddy.service
Caddy 2 is installed.
rm -rf caddy_install.sh

systemctl enable caddy.service

if [[ -f /etc/caddy/Caddyfile ]];then echo '1';else echo '0'; fi
0
systemctl restart caddy

Caddy安装完成
安装Trojan-Go...
安装Trojan-Go
curl https://raw.githubusercontent.com/proxysu/shellscript/master/trojan-go.sh yes | bash
info: Installing Trojan-go v0.10.3 for x86_64
Downloading Trojan-go archive: https://github.com/p4gefau1t/trojan-go/releases/download/v0.10.3/trojan-go-linux-amd64.zip
info: Extract the Trojan-go package to /tmp/tmp.28dkxEuCoi/ and prepare it for installation.
installed: /usr/local/bin/trojan-go
installed: /usr/share/trojan-go/geoip.dat
installed: /usr/share/trojan-go/geosite.dat
installed: /usr/local/etc/trojan-go/config.json
removed: /tmp/tmp.28dkxEuCoi/
info: Trojan-go v0.10.3 is installed.
You may need to execute a command to remove dependent software: yum remove curl unzip
Please execute the command: systemctl enable trojan-go; systemctl start trojan-go
if [[ -f /usr/local/bin/trojan-go ]];then echo '1';else echo '0'; fi
1
sed -i 's/User=nobody/User=root/g' /etc/systemd/system/trojan-go.service

sed -i 's/CapabilityBoundingSet=/#CapabilityBoundingSet=/g' /etc/systemd/system/trojan-go.service

sed -i 's/AmbientCapabilities=/#AmbientCapabilities=/g' /etc/systemd/system/trojan-go.service

systemctl daemon-reload

systemctl enable trojan-go

systemctl start trojan-go

Trojan-Go 安装完成
echo y | yum -y install socat
Loaded plugins: langpacks
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Nothing to do
echo y | yum -y install automake autoconf libtool
Loaded plugins: langpacks
Package automake-1.13.4-3.el7.noarch already installed and latest version
Package autoconf-2.69-11.el7.noarch already installed and latest version
Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Nothing to do
curl  https://get.acme.sh yes | sh
[Wed Jun  2 08:47:34 UTC 2021] Installing from online archive.
[Wed Jun  2 08:47:34 UTC 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Wed Jun  2 08:47:41 UTC 2021] Extracting master.tar.gz
安装 acme.sh 失败，请联系开发者！
安装终止，安装 acme.sh 失败，请联系开发者！
sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
command -v systemctl
/usr/bin/systemctl
command -v getenforce
/usr/sbin/getenforce
getenforce
Disabled
echo y | yum -y install socat
Loaded plugins: langpacks
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Nothing to do
echo y | yum -y install automake autoconf libtool
Loaded plugins: langpacks
Package automake-1.13.4-3.el7.noarch already installed and latest version
Package autoconf-2.69-11.el7.noarch already installed and latest version
Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Nothing to do
curl  https://get.acme.sh yes | sh
[Wed Jun  2 08:49:14 UTC 2021] Installing from online archive.
[Wed Jun  2 08:49:14 UTC 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Wed Jun  2 08:49:21 UTC 2021] Extracting master.tar.gz
安装 acme.sh 失败，请联系开发者！
systemctl stop trojan-go

systemctl stop caddy

rm -rf caddy_install.sh

curl -o caddy_install.sh https://raw.githubusercontent.com/proxysu/shellscript/master/Caddy-Naive/caddy-naive-install.sh

yes | bash caddy_install.sh uninstall
Shutting down caddy service.
Removed: /etc/systemd/system/caddy.service
Removing caddy binaries & files.
Removed: /usr/bin/caddy
Removed: /etc/caddy
Removed caddy successfully.
rm -rf caddy_install.sh

rm -rf /usr/share/caddy

rm -rf /usr/local/bin/trojan-go

rm -rf /usr/local/etc/trojan-go

acme.sh --uninstall

rm -r  ~/.acme.sh

卸载Trojan-Go完成
`

**Comment by next-autumn** [comment]
系统什么版本，比较旧了吗？
提示是解压缩时候失败了，或更新下系统版本。
