### ISSUE TITLE
安装终止，未检测到可用的IP地址

### ISSUE THREAD

**Issue by MrWater233** [proxysu/ProxySU#150]
![image](https://user-images.githubusercontent.com/45112790/120640736-68184100-c4a5-11eb-8e39-69d293ab3405.png)

**Comment by MrWater233** [comment]
请问这个怎么解决啊？

**Comment by francis5959** [comment]
同样问题，又回到2.5.6了

**Comment by hennesshuang** [comment]
![Snap3](https://user-images.githubusercontent.com/55419630/120879106-b2a7d380-c5f3-11eb-8f24-fc51337e7142.jpg)
same as you。

**Comment by next-autumn** [comment]
ping一下域名，是否能ping通到本机ip ？

**Comment by next-autumn** [comment]
> ![Snap3](https://user-images.githubusercontent.com/55419630/120879106-b2a7d380-c5f3-11eb-8f24-fc51337e7142.jpg)
> debian10，same as you。

请问是ipv6主机吗？

**Comment by next-autumn** [comment]
> 同样问题，又回到2.5.6了

请问是ipv6主机吗？

**Comment by next-autumn** [comment]
网络不好情况下出现的，如果网络畅通，重试安装就可以了。
