### ISSUE TITLE
安装完查看配置的时候，伪装域名不显示

### ISSUE THREAD

**Issue by Zhangxxl** [proxysu/ProxySU#153]
伪装域名显示的是我自己的域名， 这样不知道设置成功没有

**Comment by Zhangxxl** [comment]
![image](https://user-images.githubusercontent.com/18618523/121142634-c874fd00-c86e-11eb-80ef-f0bbce92a3ca.png)

**Comment by next-autumn** [comment]
这里不应该叫“伪装网站” 就是Host配置，这里是根据V2rayN的参照的。

![image](https://user-images.githubusercontent.com/73510229/121157305-02003500-c87c-11eb-8b92-db70044da754.png)

**Comment by Zhangxxl** [comment]
> 这里不应该叫“伪装网站” 就是Host配置，这里是根据V2rayN的配置项参照的。
> 
> ![image](https://user-images.githubusercontent.com/73510229/121157305-02003500-c87c-11eb-8b92-db70044da754.png)

这里安装的时候我是填了github的网站，但是配置导出到v2rayN后，在v2rayN的配置页面，伪装域名这一栏也是空的。这样是正常的吗？ 
![image](https://user-images.githubusercontent.com/18618523/121158383-e9dce580-c87c-11eb-96a5-288124c08445.png)
