### ISSUE TITLE
acme更改为zerossl后申请证书失败

### ISSUE THREAD

**Issue by jliveusa** [proxysu/ProxySU#154]
提示缺少email address

**Comment by ylf0925** [comment]
同样有这个问题
prompt如下

```
[Sun Jun 13 12:33:50 UTC 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Sun Jun 13 12:33:50 UTC 2021] Run pre hook:'systemctl stop caddy'
[Sun Jun 13 12:33:50 UTC 2021] Standalone mode.
[Sun Jun 13 12:33:50 UTC 2021] Create account key ok.
[Sun Jun 13 12:33:50 UTC 2021] No EAB credentials found for ZeroSSL, let's get one
[Sun Jun 13 12:33:50 UTC 2021] acme.sh is using ZeroSSL as default CA now.
[Sun Jun 13 12:33:50 UTC 2021] Please update your account with an email address first.
[Sun Jun 13 12:33:50 UTC 2021] acme.sh --register-account -m my@example.com
[Sun Jun 13 12:33:50 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Sun Jun 13 12:33:50 UTC 2021] Run post hook:'systemctl start caddy'
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
```

**Comment by ylf0925** [comment]
> 同样有这个问题
> prompt如下
> 
> ```
> [Sun Jun 13 12:33:50 UTC 2021] Using CA: https://acme.zerossl.com/v2/DV90
> [Sun Jun 13 12:33:50 UTC 2021] Run pre hook:'systemctl stop caddy'
> [Sun Jun 13 12:33:50 UTC 2021] Standalone mode.
> [Sun Jun 13 12:33:50 UTC 2021] Create account key ok.
> [Sun Jun 13 12:33:50 UTC 2021] No EAB credentials found for ZeroSSL, let's get one
> [Sun Jun 13 12:33:50 UTC 2021] acme.sh is using ZeroSSL as default CA now.
> [Sun Jun 13 12:33:50 UTC 2021] Please update your account with an email address first.
> [Sun Jun 13 12:33:50 UTC 2021] acme.sh --register-account -m my@example.com
> [Sun Jun 13 12:33:50 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
> [Sun Jun 13 12:33:50 UTC 2021] Run post hook:'systemctl start caddy'
> 申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
> 安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
> ```

已经常识过多次更换二级域名，无效

**Comment by nbagui** [comment]
我以为是自己的问题，原来确实是因为换了SSL证书服务商导致
另外，如果手工导入，证书文件是否有命名规则？实在不行，就手工导入试试

**Comment by jaysonyip** [comment]
同样有问题，用了6.10的新版，还是一样

**Comment by 1095893390** [comment]
最新版本4.0.1安装trojan同样出现证书问题

[Mon Jun 14 08:14:26 UTC 2021] Using CA: https://acme.zerossl.com/v2/DV90
[Mon Jun 14 08:14:26 UTC 2021] Run pre hook:'systemctl stop caddy'
[Mon Jun 14 08:14:26 UTC 2021] Standalone mode.
[Mon Jun 14 08:14:26 UTC 2021] No EAB credentials found for ZeroSSL, let's get one
[Mon Jun 14 08:14:26 UTC 2021] acme.sh is using ZeroSSL as default CA now.
[Mon Jun 14 08:14:26 UTC 2021] Please update your account with an email address first.
[Mon Jun 14 08:14:26 UTC 2021] acme.sh --register-account -m my@example.com
[Mon Jun 14 08:14:26 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
[Mon Jun 14 08:14:26 UTC 2021] Run post hook:'systemctl start caddy'
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

**Comment by next-autumn** [comment]
fix it .

4.0.2
