### ISSUE TITLE
证书还是失败，centos8 64bit

### ISSUE THREAD

**Issue by nethawkhu** [proxysu/ProxySU#155]
[Tue Jun 15 14:19:45 UTC 2021] Running cmd: issue
[Tue Jun 15 14:19:45 UTC 2021] _main_domain='*********.com'
[Tue Jun 15 14:19:45 UTC 2021] _alt_domains='no'
[Tue Jun 15 14:19:45 UTC 2021] Using config home:/root/.acme.sh
[Tue Jun 15 14:19:45 UTC 2021] default_acme_server
[Tue Jun 15 14:19:45 UTC 2021] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[Tue Jun 15 14:19:45 UTC 2021] DOMAIN_PATH='/root/.acme.sh/************.com'
[Tue Jun 15 14:19:45 UTC 2021] Using ACME_DIRECTORY: https://acme.zerossl.com/v2/DV90
[Tue Jun 15 14:19:45 UTC 2021] _init api for server: https://acme.zerossl.com/v2/DV90
[Tue Jun 15 14:19:45 UTC 2021] GET
[Tue Jun 15 14:19:45 UTC 2021] url='https://acme.zerossl.com/v2/DV90'
[Tue Jun 15 14:19:45 UTC 2021] timeout=
[Tue Jun 15 14:19:45 UTC 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Tue Jun 15 14:19:45 UTC 2021] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Tue Jun 15 14:19:45 UTC 2021] ret='35'
[Tue Jun 15 14:19:45 UTC 2021] Can not init api for: https://acme.zerossl.com/v2/DV90.

**Comment by next-autumn** [comment]
看日志情况，可能是80端口未开放，证书签发时候访问超时。
有些vps服务商需要后台配置，开放80和443端口。
请检查是否是这个原因。

**Comment by nethawkhu** [comment]
80端口肯定是开放的，这个vps之前用 2.5.6 的版本装过的，没有问题。

**Comment by next-autumn** [comment]
4.0.3 试试！
