### ISSUE TITLE
自有证书怎么使用啊？

### ISSUE THREAD

**Issue by crosspacific** [proxysu/ProxySU#156]
申请证书一直失败，自有证书上传了没有反应。具体怎么操作啊？

**Comment by next-autumn** [comment]
自有证书目前是安装成功后才能上传，crt和key文件打包zip上传即可。
证书申请失败请发下日志，或者到telegram群里提问。

最近较多原因，是vps服务商需要后台配置开放443和80端口，请检查一下是否是这个原因，否则上传自有证书也是无法连通。
