### ISSUE TITLE
Proxy SU 4.0.3 caddy error

### ISSUE THREAD

**Issue by rkars373n** [proxysu/ProxySU#157]
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

how to fix this problem

**Comment by next-autumn** [comment]
用什么系统版本呢？

**Comment by next-autumn** [comment]
acme.sh官方默认证书机构更换了，某些场景申请是遇到写问题。
4.0.3还原了之前的证书机构。

请尝试是否解决！

**Comment by rkars373n** [comment]
autoconf is already the newest version (2.69-11.1).
automake is already the newest version (1:1.16.1-4ubuntu6).
libtool is already the newest version (2.4.6-14).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
curl  https://get.acme.sh yes | sh
[Fri Jun 18 16:02:58 UTC 2021] Installing from online archive.
[Fri Jun 18 16:02:58 UTC 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Fri Jun 18 16:02:58 UTC 2021] Extracting master.tar.gz
[Fri Jun 18 16:02:58 UTC 2021] Installing to /root/.acme.sh
[Fri Jun 18 16:02:58 UTC 2021] Installed to /root/.acme.sh/acme.sh
[Fri Jun 18 16:02:58 UTC 2021] Installing alias to '/root/.bashrc'
[Fri Jun 18 16:02:58 UTC 2021] OK, Close and reopen your terminal to start using acme.sh
[Fri Jun 18 16:02:59 UTC 2021] Installing cron job
24 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Fri Jun 18 16:02:59 UTC 2021] Good, bash is found, so change the shebang to use bash as preferred.
[Fri Jun 18 16:02:59 UTC 2021] OK
[Fri Jun 18 16:02:59 UTC 2021] Install success!
安装 acme.sh 成功
cd ~/.acme.sh/

alias acme.sh=~/.acme.sh/acme.sh

/root/.acme.sh/acme.sh --force --debug --issue  --standalone  -d test.se7enygn.xyz --pre-hook "systemctl stop caddy"  --post-hook  "systemctl start caddy" --server letsencrypt
https://github.com/acmesh-official/acme.sh
v3.0.0
[Fri Jun 18 16:03:01 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Fri Jun 18 16:03:01 UTC 2021] Run pre hook:'systemctl stop caddy'
[Fri Jun 18 16:03:01 UTC 2021] Standalone mode.
[Fri Jun 18 16:03:01 UTC 2021] Create account key ok.
[Fri Jun 18 16:03:01 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
[Fri Jun 18 16:03:04 UTC 2021] Registered
[Fri Jun 18 16:03:04 UTC 2021] ACCOUNT_THUMBPRINT='7XC5VWdxaAhMwESGAc7Un1Tz0LGhGlSOtna2pgU7VTk'
[Fri Jun 18 16:03:04 UTC 2021] Creating domain key
[Fri Jun 18 16:03:05 UTC 2021] The domain key is here: /root/.acme.sh/test.se7enygn.xyz/test.se7enygn.xyz.key
[Fri Jun 18 16:03:05 UTC 2021] Single domain='test.se7enygn.xyz'
[Fri Jun 18 16:03:05 UTC 2021] Getting domain auth token for each domain
[Fri Jun 18 16:03:08 UTC 2021] Getting webroot for domain='test.se7enygn.xyz'
[Fri Jun 18 16:03:08 UTC 2021] Verifying: test.se7enygn.xyz
[Fri Jun 18 16:03:08 UTC 2021] Standalone mode server
<html>
<head><title>521 Origin Down</title></head>
<body bgcolor="white">
<center><h1>521 Origin Down</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
[Fri Jun 18 16:03:13 UTC 2021] Run post hook:'systemctl start caddy'
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！


i will setup in digita;l ocean server but same error 

how can i fix

**Comment by next-autumn** [comment]
can you 

> autoconf is already the newest version (2.69-11.1).
> automake is already the newest version (1:1.16.1-4ubuntu6).
> libtool is already the newest version (2.4.6-14).
> 0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
> curl https://get.acme.sh yes | sh
> [Fri Jun 18 16:02:58 UTC 2021] Installing from online archive.
> [Fri Jun 18 16:02:58 UTC 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
> [Fri Jun 18 16:02:58 UTC 2021] Extracting master.tar.gz
> [Fri Jun 18 16:02:58 UTC 2021] Installing to /root/.acme.sh
> [Fri Jun 18 16:02:58 UTC 2021] Installed to /root/.acme.sh/acme.sh
> [Fri Jun 18 16:02:58 UTC 2021] Installing alias to '/root/.bashrc'
> [Fri Jun 18 16:02:58 UTC 2021] OK, Close and reopen your terminal to start using acme.sh
> [Fri Jun 18 16:02:59 UTC 2021] Installing cron job
> 24 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
> [Fri Jun 18 16:02:59 UTC 2021] Good, bash is found, so change the shebang to use bash as preferred.
> [Fri Jun 18 16:02:59 UTC 2021] OK
> [Fri Jun 18 16:02:59 UTC 2021] Install success!
> 安装 acme.sh 成功
> cd ~/.acme.sh/
> 
> alias acme.sh=~/.acme.sh/acme.sh
> 
> /root/.acme.sh/acme.sh --force --debug --issue --standalone -d test.se7enygn.xyz --pre-hook "systemctl stop caddy" --post-hook "systemctl start caddy" --server letsencrypt
> https://github.com/acmesh-official/acme.sh
> v3.0.0
> [Fri Jun 18 16:03:01 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
> [Fri Jun 18 16:03:01 UTC 2021] Run pre hook:'systemctl stop caddy'
> [Fri Jun 18 16:03:01 UTC 2021] Standalone mode.
> [Fri Jun 18 16:03:01 UTC 2021] Create account key ok.
> [Fri Jun 18 16:03:01 UTC 2021] Registering account: https://acme-v02.api.letsencrypt.org/directory
> [Fri Jun 18 16:03:04 UTC 2021] Registered
> [Fri Jun 18 16:03:04 UTC 2021] ACCOUNT_THUMBPRINT='7XC5VWdxaAhMwESGAc7Un1Tz0LGhGlSOtna2pgU7VTk'
> [Fri Jun 18 16:03:04 UTC 2021] Creating domain key
> [Fri Jun 18 16:03:05 UTC 2021] The domain key is here: /root/.acme.sh/test.se7enygn.xyz/test.se7enygn.xyz.key
> [Fri Jun 18 16:03:05 UTC 2021] Single domain='test.se7enygn.xyz'
> [Fri Jun 18 16:03:05 UTC 2021] Getting domain auth token for each domain
> [Fri Jun 18 16:03:08 UTC 2021] Getting webroot for domain='test.se7enygn.xyz'
> [Fri Jun 18 16:03:08 UTC 2021] Verifying: test.se7enygn.xyz
> [Fri Jun 18 16:03:08 UTC 2021] Standalone mode server
> 
> <title>521 Origin Down</title>
> # 521 Origin Down
> cloudflare-nginx [Fri Jun 18 16:03:13 UTC 2021] Run post hook:'systemctl start caddy' 申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！ 安装终止，申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！
> i will setup in digita;l ocean server but same error
> 
> how can i fix

Can you contact me on telegram?

**Comment by next-autumn** [comment]
please use v4.0.4
