### ISSUE TITLE
4.0.3 XRAY 无法正常安装

### ISSUE THREAD

**Issue by Fetiz** [proxysu/ProxySU#158]
前面什么的都解析通过了，但是卡在了如下步骤大概有15min 没有变化。

`dnf install -y 'dnf-command(copr)'
Last metadata expiration check: 0:00:18 ago on Fri 18 Jun 2021 01:10:44 PM UTC.
Package dnf-plugins-core-4.0.18-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
dnf copr enable @caddy/caddy
`

请问大佬怎么处理。

**Comment by next-autumn** [comment]
看起来是caddy已经安装过了，卸载一下重装，或者重装系统试试。

但为什么停住了，是否可以到telegram上找群主看一下？

**Comment by next-autumn** [comment]
CentOS 8中执行 yum/dnf update，出现报错：Failed to set locale, defaulting to C.UTF-8

报错原因：没有设置正确的语言环境。
解决方法：
运行以下两条命令
echo "export LC_ALL=en_US.UTF-8"  >>  /etc/profile
source /etc/profile

**Comment by next-autumn** [comment]
https://github.com/proxysu/ProxySU/releases/tag/4.0.3

你好，请重新下载一下4.0.3，这个步骤中出现了一个yes/no提问，被阻断了。
