### ISSUE TITLE
不是root帐户管理员，如何安装

### ISSUE THREAD

**Issue by jamyes** [proxysu/ProxySU#163]
不是root帐户管理员，如何安装

**Comment by next-autumn** [comment]
https://github.com/proxysu/ProxySU/wiki/%E8%B0%B7%E6%AD%8C%E4%BA%91%E5%BC%80%E5%90%AFroot%E8%B4%A6%E6%88%B7%E4%B8%8E%E5%AF%86%E7%A0%81%E7%99%BB%E5%BD%95

**Comment by next-autumn** [comment]
v4.0.4 中 提供了【操作】-【启用root账户】功能
