### ISSUE TITLE
ipv6检测失败

### ISSUE THREAD

**Issue by uxgsiwy5swdo** [proxysu/ProxySU#166]
正在登录远程主机......
主机登录成功!
uname -a
Linux ip-172-26-7-141 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

检测是否运行在root权限下...
id -u
0

检测结果：OK！
if [[ -f /etc/resolv.conf.proxysu ]];then echo '1';else echo '0'; fi
0

command -v apt-get
/usr/bin/apt-get

command -v dnf

command -v yum

正在检测是否为纯ipv6主机......
curl -s https://api.ip.sb/ip --ipv4 --max-time 8

curl -s https://api.ip.sb/ip --ipv6 --max-time 8

未检测到有效的IP地址......

**Comment by next-autumn** [comment]
curl -s https://api.ip.sb/ip --ipv4 --max-time 8

curl -s https://api.ip.sb/ip --ipv6 --max-time 8

这两条命令是检测输出服务器ip的，建议自检一下。
输出服务器IP即正常，如果正常的话重试下安装。

**Comment by next-autumn** [comment]
检测IP时缺少curl组件。v4.0.4** 修复。
