### ISSUE TITLE
安装到一半的时候，突然提示失败

### ISSUE THREAD

**Issue by oudog** [proxysu/ProxySU#167]
正在登陆服务器 ...
登陆服务器成功！
sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
if [[ -f /usr/local/bin/xray ]];then echo '1';else echo '0'; fi
0
检测安装系统环境...
command -v apt
/usr/bin/apt
command -v systemctl
/usr/bin/systemctl
command -v getenforce

检测安装系统环境完成
配置服务器端口...
lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

端口配置完成
安装必要的系统工具...
apt update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [6,745 B]
Ign:3 https://apt.fury.io/caddy  InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Ign:5 https://apt.fury.io/caddy  Release
Ign:6 https://apt.fury.io/caddy  Packages
Ign:7 https://apt.fury.io/caddy  Translation-en
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Get:6 https://apt.fury.io/caddy  Packages
Get:10 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:7 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:7 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:7 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:7 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:7 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Ign:7 https://apt.fury.io/caddy  Translation-en
Ign:9 https://apt.fury.io/caddy  Translation-en_US
Fetched 341 kB in 2s (176 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
132 packages can be upgraded. Run 'apt list --upgradable' to see them.
command -v sudo
/usr/bin/sudo
command -v curl
/usr/bin/curl
command -v wget
/usr/bin/wget
command -v unzip
/usr/bin/unzip
command -v dig
/usr/bin/dig
apt install -y xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version (5.2.4-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up initramfs-tools (0.136ubuntu6) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.136ubuntu6) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-77-generic
Error 24 : Write error : cannot write compressed block 
E: mkinitramfs failure cpio 141 lz4 -9 -l 24
update-initramfs: failed for /boot/initrd.img-5.4.0-77-generic with 1.
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
command -v cron
/usr/sbin/cron
command -v lsof
/usr/bin/lsof
系统工具安装完成
检测IP6...
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
144.34.251.223
检测IP6完成
配置防火墙...
command -v firewall-cmd

command -v ufw
/usr/sbin/ufw
ufw allow 80/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 80/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 443/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 443/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 2001/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 2001/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 3001/tcp
Rules updated
Rules updated (v6)
ufw allow 3001/udp
Rules updated
Rules updated (v6)
ufw allow 4001/tcp
Rules updated
Rules updated (v6)
ufw allow 4001/udp
Rules updated
Rules updated (v6)
yes | ufw reload
Firewall not enabled (skipping reload)
防火墙配置完成
同步系统和本地时间...
rm -f /etc/localtime

ln -s /usr/share/zoneinfo/UTC /etc/localtime

date +%s
1625470379
时间同步完成
检测域名是否绑定本机IP...
dig @resolver1.opendns.com A pt.*******.cn +short -4 | grep  -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1
***。***。***。***
域名检测完成
安装Caddy...
apt install -y debian-keyring debian-archive-keyring apt-transport-https
Reading package lists...
Building dependency tree...
Reading state information...
debian-archive-keyring is already the newest version (2019.1ubuntu2).
debian-keyring is already the newest version (2020.03.24).
apt-transport-https is already the newest version (2.0.6).
0 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up initramfs-tools (0.136ubuntu6) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.136ubuntu6) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-77-generic
Error 24 : Write error : cannot write compressed block 
E: mkinitramfs failure cpio 141 lz4 -9 -l 24
update-initramfs: failed for /boot/initrd.img-5.4.0-77-generic with 1.
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
echo yes | curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo apt-key add -
OK
echo yes | curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
# Source: Caddy
# Site: https://github.com/caddyserver/caddy
# Repository: Caddy / stable
# Description: Fast, multi-platform web server with automatic HTTPS

deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main

deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
sudo apt -y update
Get:1 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [6,745 B]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Ign:3 https://apt.fury.io/caddy  InRelease
Ign:4 https://apt.fury.io/caddy  Release
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Ign:6 https://apt.fury.io/caddy  Packages
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Ign:8 https://apt.fury.io/caddy  Translation-en
Get:6 https://apt.fury.io/caddy  Packages
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Ign:8 https://apt.fury.io/caddy  Translation-en
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Get:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Ign:8 https://apt.fury.io/caddy  Translation-en
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Ign:8 https://apt.fury.io/caddy  Translation-en
Get:10 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Ign:8 https://apt.fury.io/caddy  Translation-en
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Ign:8 https://apt.fury.io/caddy  Translation-en
Ign:7 https://apt.fury.io/caddy  Translation-en_US
Ign:8 https://apt.fury.io/caddy  Translation-en
Fetched 341 kB in 2s (220 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
132 packages can be upgraded. Run 'apt list --upgradable' to see them.
sudo apt install -y caddy
安装终止，An established connection was aborted by the server.

**Comment by next-autumn** [comment]
An established connection was aborted by the server.

本地和服务器断开了链接，可能两个原因
1. 本地和服务器之间网络不好，丢包高。建议加代理或者重试。
2. 服务器内存高，如果不是新系统，建议重装系统。

**Comment by next-autumn** [comment]
在新版本中排查了一些【连接断开】的问题，及【证书申请失败】问题， 欢迎试用v4.0.4。

支持 centos7/8   debian/9/10  ubuntu 18/20

**Comment by oudog** [comment]
谢谢大家的帮忙！
我把原来的Ubuntu换成 debian之后，重装成功了！
