### ISSUE TITLE
请问下能和宝塔或者aapanel面板共存或者结合吗？

### ISSUE THREAD

**Issue by iseeyo** [proxysu/ProxySU#169]
比如安装流量特征与Xray流量特征相同的网盘站点，需要用到aapanel相应环境。ProxySU自带的Caddy会和aapanel的Nginx冲突，能否为aapanel环境提供一个兼容方案，比如安装时不安装Caddy而是共用aapanel的Nginx环境呢？

**Comment by Asrielwiki** [comment]
可以啊，只要端口不一样就可以
