### ISSUE TITLE
伪装网站上传用什么格式

### ISSUE THREAD

**Issue by yishan2019** [proxysu/ProxySU#170]
伪装网站上传用什么格式？是web.zip还是不需要压缩？

**Comment by next-autumn** [comment]
必须是静态网站，根目录下必须有index.html，php之类的不行。

**Comment by OleStore** [comment]
> 必须是静态网站，根目录下必须有index.html，php之类的不行。

早期版本不是有系统工具，启动root证书密钥登录，这小工具贼方便啊，新版本之后都没了

**Comment by next-autumn** [comment]
> > 必须是静态网站，根目录下必须有index.html，php之类的不行。
> 
> 早期版本不是有系统工具，启动root证书密钥登录，这小工具贼方便啊，新版本之后都没了

4.0.4 【操作】-【启用Root账户】

**Comment by OleStore** [comment]
> > > 必须是静态网站，根目录下必须有index.html，php之类的不行。
> > 
> > 
> > 早期版本不是有系统工具，启动root证书密钥登录，这小工具贼方便啊，新版本之后都没了
> 
> 4.0.4 【操作】-【启用Root账户】

大佬，我说的是root 密钥证书登录，不是启用root
