### ISSUE TITLE
上传已有证书后一键安装失败

### ISSUE THREAD

**Issue by 716c** [proxysu/ProxySU#174]
[Uploading 2021-07-13 11-37.xary.txt…]()

需要修改ssl证书私钥文件名为*.key才能够上传。上传后，一键安装代理会卡在证书申请的地方。导致安装失败。卸载代理后重新尝试亦是如此。

**Comment by 716c** [comment]
很喜欢这个工具。请问能否识别其它格式证书（如：.PEM）？可否加入gRPC？另外，添加主机为xray后。里面各种加密方式是否可以多选？之前多选出现搭建好服务器后链接导入客户端但无法连通的情况。单选VLESS mKCP也是搭建后无法连通的情况。
[2021-07-14 04-20.xary.txt](https://github.com/proxysu/ProxySU/files/6815188/2021-07-14.04-20.xary.txt)

**Comment by next-autumn** [comment]
用新系统，先一键安装，再替换证书。

无法连通可以到Telegram群里私聊群主，看看是什么情况。

**Comment by next-autumn** [comment]
> 很喜欢这个工具。请问能否识别其它格式证书（如：.PEM）？可否加入gRPC？另外，添加主机为xray后。里面各种加密方式是否可以多选？之前多选出现搭建好服务器后链接导入客户端但无法连通的情况。单选VLESS mKCP也是搭建后无法连通的情况。
> [2021-07-14 04-20.xary.txt](https://github.com/proxysu/ProxySU/files/6815188/2021-07-14.04-20.xary.txt)

v4.0.4 已经加入了gRPC

**Comment by 716c** [comment]
谢谢！
