### ISSUE TITLE
一键安装正常使用。服务器重启后，Xray没有随系统启动。

### ISSUE THREAD

**Issue by o-00-o** [proxysu/ProxySU#176]
请问用什么命令，可以查看Xray的管理后台？查看、终止、启动Xray。

**Comment by next-autumn** [comment]
xray安装是直接开启了随即启动的，xray没有管理后台。

您的情况可以试一下

允许开机启动
systemctl enable xray

查看状态
systemctl status xray

停止
systemctl stop xray

启动
systemctl restart xray

**Comment by cheneyxx** [comment]
有bug啊 服务器安装bbr plus重启后 就启动不了xray了

**Comment by cheneyxx** [comment]
Unit xray.service could not be found.
