### ISSUE TITLE
最新版本 修改 xray的443端口不启作用

### ISSUE THREAD

**Issue by fssl168** [proxysu/ProxySU#179]
你好，开发者
我修改最新版v4.0.4的xray端口后，后台更新不启作用。
包括新设置的xray端口，原端口443均不启作用； 如果是一定不能更改的话，就把那个选项禁用了吧
注：
因为现在梯子越来越高，运营商或GFW禁用了443端口，国内IP无法访用国外VPS的443端口，没办法只能更改443为其他端口，建议还是允行自行更改443端口，可以使用Nginx 的Server stream转发本地的443响应或者使用caddy 的端口转发技术实现。

**Comment by next-autumn** [comment]
v4.0.4.1 修复了此问题。
