### ISSUE TITLE
使用vmess/vless mKCP在手机上连接服务器后翻墙无效

### ISSUE THREAD

**Issue by fssl168** [proxysu/ProxySU#180]
我kitsunebi使用vmess/vless mKCP在手机上无效
我从电脑扫描生成的二维码，手机上可以添加和修改，客户端也正常连接服务器，可是手机无法正常翻墙。不知是什么原因。
注：
我使用的手机客户端是kitsunebi

**Comment by next-autumn** [comment]
这个请到kitsunebi提问
