### ISSUE TITLE
请问为什么我用你这个软件安装完后还没开始用，流量马上就超了！

### ISSUE THREAD

**Issue by LLQQHH** [proxysu/ProxySU#181]
试过两次了，我一开始还有200g流量，然后开启你这个软件自动安装，安装好后，我要去用，发现无法上网，后来去后台一看，好家伙200G一下子就没了！请问这个软件安装的会下载很多东西吗，我用服务器是双向收取流量的！这是什么原因，我之前用别的方法安装，不会这样的！

**Comment by next-autumn** [comment]
这个软件和其他安装脚本基本一样，都是开源的，都是xray、caddy或nginx这几样东西。
200g流量还是检查一下流量用在哪了，没见过这个情况。

**Comment by next-autumn** [comment]
https://www.ryankgrow.com/so/k/%E5%8F%91%E9%82%AE%E4%BB%B6%E7%9A%84vps

有vps被攻击25邮件端口的情况，如果没有防火墙，安装并开启防火墙，再安装脚本。
