### ISSUE TITLE
Xray-Core安装失败，请联系开发者 安装终止，Xray-Core安装失败，请联系开发者

### ISSUE THREAD

**Issue by CharlesTaino1** [proxysu/ProxySU#184]
正在登陆服务器 ...
登陆服务器成功！
sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
uname -m
x86_64
command -v apt
/usr/bin/apt
command -v systemctl
/bin/systemctl
command -v getenforce

systemctl stop caddy

systemctl stop xray

lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

lsof -n -P -i :2001 | grep LISTEN

lsof -n -P -i :3001 | grep LISTEN

lsof -n -P -i :4001 | grep LISTEN

command -v firewall-cmd

command -v ufw

apt install -y ufw

echo y | ufw enable

ufw allow 29085/tcp

ufw allow 29085/udp

yes | ufw reload

command -v firewall-cmd

command -v ufw

apt install -y ufw

echo y | ufw enable

ufw allow 80/tcp

ufw allow 80/udp

ufw allow 443/tcp

ufw allow 443/udp

ufw allow 2001/tcp

ufw allow 2001/udp

ufw allow 3001/tcp

ufw allow 3001/udp

ufw allow 4001/tcp

ufw allow 4001/udp

yes | ufw reload

rm -rf /usr/local/etc/xray/config.json

sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
uname -m
x86_64
command -v systemctl
/bin/systemctl
command -v getenforce

bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
info: Installing Xray v1.4.2 for x86_64
error: Installation of unzip failed, please check your network.
systemctl restart xray

************ 更新xray内核完成 ************
sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

id -u
0
if [[ -f /usr/local/bin/xray ]];then echo '1';else echo '0'; fi
0
检测安装系统环境...
uname -m
x86_64
command -v systemctl
/bin/systemctl
command -v getenforce

检测安装系统环境完成
安装必要的系统工具...
apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists...
Building dependency tree...
Reading state information...
163 packages can be upgraded. Run 'apt list --upgradable' to see them.
command -v sudo
/usr/bin/sudo
command -v curl
/usr/bin/curl
command -v wget
/usr/bin/wget
command -v unzip

apt install -y unzip

command -v dig

apt install -y dnsutils

apt install -y xz-utils

command -v cron
/usr/sbin/cron
command -v lsof

apt install -y lsof

系统工具安装完成
配置防火墙...
lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

lsof -n -P -i :2001 | grep LISTEN

lsof -n -P -i :3001 | grep LISTEN

lsof -n -P -i :4001 | grep LISTEN

command -v firewall-cmd

command -v ufw

apt install -y ufw

echo y | ufw enable

ufw allow 29085/tcp

ufw allow 29085/udp

yes | ufw reload

command -v firewall-cmd

command -v ufw

apt install -y ufw

echo y | ufw enable

ufw allow 80/tcp

ufw allow 80/udp

ufw allow 443/tcp

ufw allow 443/udp

ufw allow 2001/tcp

ufw allow 2001/udp

ufw allow 3001/tcp

ufw allow 3001/udp

ufw allow 4001/tcp

ufw allow 4001/udp

yes | ufw reload

防火墙配置完成
检测网络环境
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
216.24.189.218
检测网络环境完成
同步系统和本地时间...
rm -f /etc/localtime

ln -s /usr/share/zoneinfo/UTC /etc/localtime

date +%s
1628518328
时间同步完成
检测域名是否绑定本机IP...
dig @resolver1.opendns.com A cnet.novelbird.com +short -4 | grep  -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1

域名检测完成
安装Caddy...
rm -rf caddy.tar.gz

rm -rf /etc/caddy

rm -rf /usr/share/caddy

wget -O caddy.tar.gz https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_amd64.tar.gz

mkdir /etc/caddy

tar -zxvf caddy.tar.gz -C /etc/caddy
LICENSE
README.md
caddy
cp -rf /etc/caddy/caddy /usr/bin

systemctl daemon-reload

systemctl enable caddy

mkdir /usr/share/caddy

if [[ -f /usr/bin/caddy ]];then echo '1';else echo '0'; fi
1
Caddy安装完成
安装Xray-Core...
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
info: Installing Xray v1.4.2 for x86_64
error: Installation of unzip failed, please check your network.
if [[ -f /usr/local/bin/xray ]];then echo '1';else echo '0'; fi
0
Xray-Core安装失败，请联系开发者
安装终止，Xray-Core安装失败，请联系开发者

**Comment by next-autumn** [comment]
error: Installation of unzip failed, please check your network.
安装xray提示的错误，检查一下你的主机为什么安装不了unzip
最好用纯净的 ubuntu20 或 debian10 安装
