### ISSUE TITLE
已解决：安装过程中，连接失败，之后ssh也连接不上。

### ISSUE THREAD

**Issue by next-autumn** [proxysu/ProxySU#188]
问题：
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
之后ssh也连接不上。

解决：
如果是2021/8/25日之前下载的
请重新下载 v4.1.0

https://github.com/proxysu/ProxySU/releases/download/v4.1.1/ProxySU.zip

**Comment by next-autumn** [comment]
.

**Comment by yoligo9638** [comment]
小心眼的作者死爹妈，想吃瓜的进来看看。以后别得罪小人。

我私聊了作者，最后没有回复作者信息并删除了它（没错是畜生）和我的会话。

作者就把我从它的群组中删除了。

我用小号联系了作者，作者问我，是不是很委屈、很无奈。其实看到这个消息，我有点想笑的，看看这小人得志的样子，，估计在现实生活中，总是被针对才会这个样子吧。

我只是想不明白，我不回复你，删除了你和我的会话（个人习惯），和你把我从群组你里面删除，这是两件事情吧？？你是有多小心眼，才会这样做呢？

而且，我用小号骂你了，估计你也骂我了（因为我骂完后把你拉黑名单了，过了一会才取消黑名单），非要等着我骂你下一句，你才把我拉黑，你是非要我已读吗？

尽然你觉得这两件事情可以混在一起，那么我在 github 上骂你，我觉得也没什么不妥的。

我每天都会骂你，，这个号没了就用下一个号。直到你关闭项目或者关闭 Issues。

> 不仅拉黑我，还举报我的 TG，也是服了。你说就你这小心眼，估计找个女朋友都一直怀疑你女朋友绿了你，哈哈。

**Comment by bohija3547** [comment]
小心眼的作者死爹妈，想吃瓜的进来看看。以后别得罪小人。

我私聊了作者，最后没有回复作者信息并删除了它（没错是畜生）和我的会话。

作者就把我从它的群组中删除了。

我用小号联系了作者，作者问我，是不是很委屈、很无奈。其实看到这个消息，我有点想笑的，看看这小人得志的样子，，估计在现实生活中，总是被针对才会这个样子吧。

我只是想不明白，我不回复你，删除了你和我的会话（个人习惯），和你把我从群组你里面删除，这是两件事情吧？？你是有多小心眼，才会这样做呢？

而且，我用小号骂你了，估计你也骂我了（因为我骂完后把你拉黑名单了，过了一会才取消黑名单），非要等着我骂你下一句，你才把我拉黑，你是非要我已读吗？

尽然你觉得这两件事情可以混在一起，那么我在 github 上骂你，我觉得也没什么不妥的。

我每天都会骂你，，这个号没了就用下一个号。直到你关闭项目或者关闭 Issues。

> 不仅拉黑我，还举报我的 TG，也是服了。你说就你这小心眼，估计找个女朋友都一直怀疑你女朋友绿了你，哈哈。

**Comment by 69bb2c1126d6** [comment]
小心眼的作者死爹妈，想吃瓜的进来看看。以后别得罪小人。

我私聊了作者，最后没有回复作者信息并删除了它（没错是畜生）和我的会话。

作者就把我从它的群组中删除了。

我用小号联系了作者，作者问我，是不是很委屈、很无奈。其实看到这个消息，我有点想笑的，看看这小人得志的样子，，估计在现实生活中，总是被针对才会这个样子吧。

我只是想不明白，我不回复你，删除了你和我的会话（个人习惯），和你把我从群组你里面删除，这是两件事情吧？？你是有多小心眼，才会这样做呢？

而且，我用小号骂你了，估计你也骂我了（因为我骂完后把你拉黑名单了，过了一会才取消黑名单），非要等着我骂你下一句，你才把我拉黑，你是非要我已读吗？

尽然你觉得这两件事情可以混在一起，那么我在 github 上骂你，我觉得也没什么不妥的。

我每天都会骂你，，这个号没了就用下一个号。直到你关闭项目或者关闭 Issues。

> 不仅拉黑我，还举报我的 TG，也是服了。你说就你这小心眼，估计找个女朋友都一直怀疑你女朋友绿了你，哈哈。

**Comment by 5q0pxnyf** [comment]
小心眼的作者死爹妈，想吃瓜的进来看看。以后别得罪小人。

我私聊了作者，最后没有回复作者信息并删除了它（没错是畜生）和我的会话。

作者就把我从它的群组中删除了。

我用小号联系了作者，作者问我，是不是很委屈、很无奈。其实看到这个消息，我有点想笑的，看看这小人得志的样子，，估计在现实生活中，总是被针对才会这个样子吧。

我只是想不明白，我不回复你，删除了你和我的会话（个人习惯），和你把我从群组你里面删除，这是两件事情吧？？你是有多小心眼，才会这样做呢？

而且，我用小号骂你了，估计你也骂我了（因为我骂完后把你拉黑名单了，过了一会才取消黑名单），非要等着我骂你下一句，你才把我拉黑，你是非要我已读吗？

尽然你觉得这两件事情可以混在一起，那么我在 github 上骂你，我觉得也没什么不妥的。

我每天都会骂你，，这个号没了就用下一个号。直到你关闭项目或者关闭 Issues。

> 不仅拉黑我，还举报我的 TG，也是服了。你说就你这小心眼，估计找个女朋友都一直怀疑你女朋友绿了你，哈哈。
