### ISSUE TITLE
正在与服务器建立连接 连接失败，由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by WoChen5770** [proxysu/ProxySU#192]
卡在这，用管理员身份允许ProxySU也不行。
用其他ssh连接工具试了可以。
使用的版本是最新的4.1.1，刚刚下载的

**Comment by WoChen5770** [comment]
原因找到了，不能用非22端口，我把ssh的端口改回22就可以连了。
也就是说，proxysu上主机编辑的端口不生效

**Comment by 10ta** [comment]
遇到了同样的问题。

**Comment by next-autumn** [comment]
https://github.com/proxysu/ProxySU/issues/188
