### ISSUE TITLE
ss安装成功，但是无法使用

### ISSUE THREAD

**Issue by zakizou** [proxysu/ProxySU#194]
5. 同步系统和本地时间
rm -f /etc/localtime

ln -s /usr/share/zoneinfo/UTC /etc/localtime

date +%s
1630475512
5. 安装Caddy服务器
rm -rf caddy.tar.gz

rm -rf /etc/caddy

rm -rf /usr/share/caddy

wget -O caddy.tar.gz https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_amd64.tar.gz

mkdir /etc/caddy

tar -zxvf caddy.tar.gz -C /etc/caddy
LICENSE
README.md
caddy
cp -rf /etc/caddy/caddy /usr/bin

systemctl daemon-reload

systemctl enable caddy

mkdir /usr/share/caddy

chmod 775 /usr/share/caddy

if [[ -f /usr/bin/caddy ]];then echo '1';else echo '0'; fi
1
6. 安装V2ray-Core
开始安装V2ray-Core
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
info: Installing V2Ray v4.41.1 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.41.1/v2ray-linux-64.zip
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.41.1/v2ray-linux-64.zip.dgst
info: Extract the V2Ray package to /tmp/tmp.7vr36aI3tN and prepare it for installation.
info: Systemd service files have been installed successfully!
warning: The following are the actual parameters for the v2ray service startup.
warning: Please make sure the configuration file path is correctly set.
# /etc/systemd/system/v2ray.service
[Unit]
Description=V2Ray Service
Documentation=https://www.v2fly.org/
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/v2ray.service.d/10-donot_touch_single_conf.conf
# In case you have a good reason to do so, duplicate this file in the same directory and make your customizes there.
# Or all changes you made will be lost!  # Refer: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

installed: /usr/local/bin/v2ray
installed: /usr/local/bin/v2ctl
installed: /usr/local/share/v2ray/geoip.dat
installed: /usr/local/share/v2ray/geosite.dat
installed: /etc/systemd/system/v2ray.service
installed: /etc/systemd/system/v2ray@.service
removed: /tmp/tmp.7vr36aI3tN
info: V2Ray v4.41.1 is installed.
You may need to execute a command to remove dependent software: apt purge curl unzip
Please execute the command: systemctl enable v2ray; systemctl start v2ray
if [[ -f /usr/local/bin/v2ray ]];then echo '1';else echo '0'; fi
1
设置V2ray-Core权限
sed -i 's/User=nobody/User=root/g' /etc/systemd/system/v2ray.service

sed -i 's/CapabilityBoundingSet=/#CapabilityBoundingSet=/g' /etc/systemd/system/v2ray.service

sed -i 's/AmbientCapabilities=/#AmbientCapabilities=/g' /etc/systemd/system/v2ray.service

systemctl daemon-reload

systemctl enable v2ray

if [[ -f /usr/local/etc/v2ray/config.json ]];then echo '1';else echo '0'; fi
1
mv /usr/local/etc/v2ray/config.json /usr/local/etc/v2ray/config.json.1

生成v2ray服务器配置文件
7. 上传Web服务器配置
if [[ -f /etc/caddy/Caddyfile ]];then echo '1';else echo '0'; fi
1
mv /etc/caddy/Caddyfile /etc/caddy/Caddyfile.back

8. 启动BBR
检查系统是否满足启动BBR条件
uname -r
4.19.0-16-cloud-amd64
sysctl net.ipv4.tcp_congestion_control | grep bbr
net.ipv4.tcp_congestion_control = bbr
重启V2ray服务
systemctl restart caddy

systemctl restart v2ray

安装成功

**Comment by zakizou** [comment]
试了vmess mkcp安装成功，还是不能用，小白，求指导，没有域名 免费的海外aws

**Comment by next-autumn** [comment]
请到Telegram群里找群主看下具体情况。
