### ISSUE TITLE
【已修复】搬瓦工无法连接ssh

### ISSUE THREAD

**Issue by ITdesk01** [proxysu/ProxySU#197]
ip可以正常ping通。用putty也能正常登陆，域名没有代理
![image](https://user-images.githubusercontent.com/38835844/132272819-38d387ff-cd75-44f9-8f35-01e88a8bb0c0.png)

**Comment by next-autumn** [comment]
fixed

https://github.com/proxysu/ProxySU/releases/tag/v4.1.3

**Comment by ITdesk01** [comment]
可以正常用了
