### ISSUE TITLE
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

### ISSUE THREAD

**Issue by ploughbetty** [proxysu/ProxySU#200]
正在申请证书
/root/.acme.sh/acme.sh --force --debug --issue  --standalone  -d fs.lzww.xyz  --pre-hook "systemctl stop caddy"  --post-hook  "systemctl start caddy" --server letsencrypt
https://github.com/acmesh-official/acme.sh
v3.0.1
[Thu Oct 14 04:08:58 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:08:58 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:09:18 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:09:18 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:09:38 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:09:38 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:09:58 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:09:58 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:10:19 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:10:19 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:10:39 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:10:39 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:10:59 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:10:59 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:11:20 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:11:20 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:11:40 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:11:40 UTC 2021] Sleep 10 and retry.
[Thu Oct 14 04:12:00 UTC 2021] Can not init api for: https://acme-v02.api.letsencrypt.org/directory.
[Thu Oct 14 04:12:00 UTC 2021] Sleep 10 and retry.
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

**Comment by next-autumn** [comment]
1. 检查一下主机能否访问 https://acme-v02.api.letsencrypt.org/directory 地址.
2. 检查一下安全组80 443端口是否开放.
