### ISSUE TITLE
安装MTP后没有生成秘钥

### ISSUE THREAD

**Issue by carmo2011** [proxysu/ProxySU#203]
![image](https://user-images.githubusercontent.com/87646057/139074400-5ac440fa-754d-4a47-bad4-567b26b7534c.png)

**Comment by 8884361** [comment]
MTProto就不要用了，精准识别

**Comment by MisCusi2023** [comment]
已经修复相关问题。请使用v4.1.9+
现在墙真的是狠，流量有一点特征，就完蛋。
