### ISSUE TITLE
Xray-Core安装失败，请联系开发者 这个如何解决

### ISSUE THREAD

**Issue by jock0123** [proxysu/ProxySU#204]
1. 检测系统环境
检测CPU架构
uname -m
x86_64
检测系统安装命令
检测Systemctl
command -v systemctl
/usr/bin/systemctl
检测SELinux
command -v getenforce

2. 安装必要的系统工具
安装sudo工具
command -v sudo
/usr/bin/sudo
安装curl工具
command -v curl
/usr/bin/curl
安装wget工具
command -v wget
/usr/bin/wget
安装ping工具
command -v ping
/usr/bin/ping
安装unzip工具
command -v unzip

apt install -y unzip
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 172 kB of archives.
After this operation, 580 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian buster/main amd64 unzip amd64 6.0-23+deb10u1
  404  Not Found [IP: 151.101.42.132 80]
安装cron工具
command -v cron
/usr/sbin/cron
安装lsof工具
command -v lsof
/usr/bin/lsof
安装systemd工具
command -v systemd
/usr/bin/systemd
3. 配置防火墙
释放被占用的端口
lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

开放需要的端口
command -v firewall-cmd

command -v ufw
/usr/sbin/ufw
ufw allow 22/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
ufw allow 80/tcp
Rule added
Rule added (v6)
ufw allow 80/udp
Rule added
Rule added (v6)
ufw allow 443/tcp
Rule added
Rule added (v6)
ufw allow 443/udp
Rule added
Rule added (v6)
yes | ufw reload
Firewall reloaded
4. 检测网络环境
检测IPv4
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
45.13.244.66
IPv4地址为45.13.244.66
5. 同步系统和本地时间
rm -f /etc/localtime

ln -s /usr/share/zoneinfo/UTC /etc/localtime

date +%s
1635942473
5. 安装Caddy服务器
rm -rf caddy.tar.gz

rm -rf /etc/caddy

rm -rf /usr/share/caddy

wget -O caddy.tar.gz https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_amd64.tar.gz

mkdir /etc/caddy

tar -zxvf caddy.tar.gz -C /etc/caddy
LICENSE
README.md
caddy
cp -rf /etc/caddy/caddy /usr/bin

systemctl daemon-reload

systemctl enable caddy

mkdir /usr/share/caddy

chmod 775 /usr/share/caddy

if [[ -f /usr/bin/caddy ]];then echo '1';else echo '0'; fi
1
6. 安装Xray-Core
开始安装Xray-Core
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
info: Installing Xray v1.4.5 for x86_64
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 172 kB of archives.
After this operation, 580 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian buster/main amd64 unzip amd64 6.0-23+deb10u1
  404  Not Found [IP: 151.101.26.132 80]
error: Installation of unzip failed, please check your network.
if [[ -f /usr/local/bin/xray ]];then echo '1';else echo '0'; fi
0
Xray-Core安装失败，请联系开发者
![24O0PH0_QMHW~6VZAV{ABXC jpg](https://user-images.githubusercontent.com/93657108/140062019-5ae63db3-6391-4084-991d-e7d24cdeaea4.png)

**Comment by next-autumn** [comment]
apt update之后再安装试试

**Comment by xlon72** [comment]
换个系统看看，centos7试试

**Comment by chmdir** [comment]
> apt update之后再安装试试

我也是Xray-Core安装失败。
apt update之后 安装 成功
