### ISSUE TITLE
顺利安装无报错，但无法访问伪装网页

### ISSUE THREAD

**Issue by kobehuanghai** [proxysu/ProxySU#206]
Debian 10/11顺利安装无报错
访问伪装网页的时候报错
ERR_TOO_MANY_REDIRECTS
经过搜索看到类似问题解决方案是将Cloudflare SSL config 设为 Full 或者 Full(strict)
所以猜测可能是证书申请的问题？

**Comment by next-autumn** [comment]
cloudflare 监听 https，到服务器就必须是https，服务器如果接收到是http，就会跳转到https（这样就又回到了cloudflare），造成循环跳转。
