### ISSUE TITLE
第三个模式Vless over WS with TLS在服务器重启后，xray服务不会自动启动

### ISSUE THREAD

**Issue by wcmiracle** [proxysu/ProxySU#207]
如题，我每次一重启服务器后翻墙就不管用了，连接失败。最后排查出问题是xray重启后不会自启动。。。

还有，安装完后，弹出的节点配置信息，直接复制链接是不行的，因为协议那里是tcp不是ws，得手动选择第三个配置才行

恳请更新。。

**Comment by next-autumn** [comment]
mark 忙了这阵子更新

**Comment by next-autumn** [comment]
可能不是这个原因
