### ISSUE TITLE
天翼云的香港服务器是不是不能使用

### ISSUE THREAD

**Issue by cgxrhome** [proxysu/ProxySU#210]
安装时申请SSL证书都不成功，换了云主机，换了域名 换了IP都不行，手动上传证书也不能使用
![acc24a63397961ead5b3c581281ecc5](https://user-images.githubusercontent.com/83076205/144704712-e453de79-7ca9-4e36-a53f-d8a1e595c888.png)
天翼云封了80和443，8080 8443 端口，是不是这个影响 
![photo_2021-12-04_17-37-34](https://user-images.githubusercontent.com/83076205/144704831-e52aca07-6f88-4d29-89bc-f6d396d90cba.jpg)
？DD了 debian 10 和ubuntu 20这两个系统都不行，

**Comment by cgxrhome** [comment]
DD了 debian 10 和ubuntu 20这两个系统都不行

**Comment by cgxrhome** [comment]
试了一下，配置时把443改成了其它端口，再手动上传证书。还是不行

**Comment by next-autumn** [comment]
换域名

**Comment by next-autumn** [comment]
是的 安装SSL证书需要80端口验证域名服务器
