### ISSUE TITLE
caddy  激活失败

### ISSUE THREAD

**Issue by chmdir** [proxysu/ProxySU#211]
DEBIAN10 ，4.1.4版本,XRAY类型除了SS,都勾了
![image](https://user-images.githubusercontent.com/64223803/144798449-eb3ec3b4-9d76-4fe2-95ec-2827f9525e59.png)

root@vm358480:~# systemctl status caddy
● caddy.service - Caddy
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-12-06 05:27:15 UTC; 55min ago
     Docs: https://caddyserver.com/docs/
  Process: 21690 ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
 Main PID: 21690 (code=exited, status=1/FAILURE)

Dec 06 05:27:15 vm358480 caddy[21690]: LOGNAME=root
Dec 06 05:27:15 vm358480 caddy[21690]: USER=root
Dec 06 05:27:15 vm358480 caddy[21690]: SHELL=/bin/sh
Dec 06 05:27:15 vm358480 caddy[21690]: INVOCATION_ID=2074450a3ed84fd7906ab9f554f434a3
Dec 06 05:27:15 vm358480 caddy[21690]: JOURNAL_STREAM=9:7883751
Dec 06 05:27:15 vm358480 caddy[21690]: {"level":"info","ts":1638768435.2729063,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Dec 06 05:27:15 vm358480 caddy[21690]: {"level":"warn","ts":1638768435.2759254,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
Dec 06 05:27:15 vm358480 caddy[21690]: run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
Dec 06 05:27:15 vm358480 systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 05:27:15 vm358480 systemd[1]: caddy.service: Failed with result 'exit-code'.
-------------------caddy里面的代码-----------
:8080 {
    root * /usr/share/caddy
    file_server
    reverse_proxy http://wrc.com { 
        header_up Host wrc.com 
    }
}

123456.12345678.xyz:80 {
    redir https://123456.12345678.xyz.{uri}
}
-------------------------------------------------
大佬帮看下

**Comment by next-autumn** [comment]
Dec 06 05:27:15 vm358480 caddy[21690]: run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use

针对这句检查一下  端口占用情况？

**Comment by chmdir** [comment]
![image](https://user-images.githubusercontent.com/64223803/145699499-8056ef6f-77d3-4954-896b-3049463165c8.png)
中caddy用的端口

**Comment by next-autumn** [comment]
bind: address already in use
是指  配置文件中用到的端口 和 80 443之类的被占用

**Comment by chmdir** [comment]
那就奇怪 了,空白VPS 第一个装这个代理
