### ISSUE TITLE
碰到一个奇怪的问题，每保存安装一次就自动增加一个同样的uuid

### ISSUE THREAD

**Issue by hujiao80** [proxysu/ProxySU#213]
最近到部署时碰到新建服务器保存并安装后，xray无法启动，检查配置文件发现配置文件中每个配置字段都多了一个空白的id。
![image](https://user-images.githubusercontent.com/21103565/146633524-c131ed9b-6d1b-482d-bc2b-3b5c48fd12ae.png)

手动删除后多余的空白id后xray正常，后续每使用更新配置功能一次就会多出一个相同的id
![image](https://user-images.githubusercontent.com/21103565/146633575-5d23b614-67ac-47f5-be08-d9222fb23508.png)

服务器配置多用户这里也同时不断新增uuid，手动删除多余uuid后再安装问题还是重复出现
![image](https://user-images.githubusercontent.com/21103565/146633647-4049412c-fea1-4a30-a6d3-4b48adc8f6be.png)

服务选择的模式如下图：
![image](https://user-images.githubusercontent.com/21103565/146633706-94921d13-270c-4d41-a129-c266088312a9.png)

**Comment by next-autumn** [comment]
请问是哪个版本？
我记得前几个版本中，处理过这样的bug。

**Comment by hujiao80** [comment]
4.1.3和4.1.4都遇到同样的问题

**Comment by CHNTDCS** [comment]
我用4.13也有这个问题。

**Comment by PandaEgg** [comment]
我也遇到这种问题。

**Comment by barney2022** [comment]
我也遇到这种问题，另外我发现如果之前配置了其他模式，取消打√后更新配置，原来的配置代码依然在服务端的配置文件里

**Comment by next-autumn** [comment]
v4.1.5 fixed
