### ISSUE TITLE
新版ProxySU给vps安装xray，vps中的Caddyfile如何设置，才能访问vps中的文件

### ISSUE THREAD

**Issue by RodmanWang** [proxysu/ProxySU#214]
原来用2.5.6版，Caddyfile内容如下：

xxx.xxx.top {
    root * /usr/share/caddy
    file_server
    tls {
        protocols tls1.2 tls1.3
        ciphers TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        curves x25519
    }
    @xray_websocket {
        path /news
        header Connection *Upgrade*
        header Upgrade websocket
    }
    reverse_proxy @xray_websocket localhost:10000
    reverse_proxy http://english.cctv.com {
    header_up Host english.cctv.com
    }
}

ssr.xxx.top/xxx=1 {
    tls /etc/caddy/ssl/https.cer /etc/caddy/ssl/https.key
    import xxx=1/ssr.txt
}

浏览器输入https://ssr.xxx.top/xxx=1 ,可以显示ssr.txt中的内容

好久没更新，现在用新版之后，Caddyfile添加代码
:8080 {
    root * /usr/share/caddy
    file_server
    reverse_proxy http://english.cctv.com { 
        header_up Host english.cctv.com 
    }
}

xxx.xxx.top {
    redir https://xxx.xxx.top{uri}
}

ssr.xxx.top/xxx=1 {
    tls /etc/caddy/ssl/https.cer /etc/caddy/ssl/https.key
    import xxx=1/ssr.txt
}

无法访问ssr.txt内容，打开显示的实际是伪装网站，即cctv

**Comment by next-autumn** [comment]
root * /usr/share/caddy

把要访问的文件放在 /usr/share/caddy 下

**Comment by RodmanWang** [comment]
谢谢
