### ISSUE TITLE
4.14版本提示Xray-core安装失败

### ISSUE THREAD

**Issue by timerainers** [proxysu/ProxySU#225]
vps上安装了centos 8.0，使用最新的4.1.4版本安装。执行到Xray-core安装开始弹出安装失败，要求联系开发者。是因为Xray-core核心更新的问题么？

**Comment by next-autumn** [comment]
centos系统有些版本测试有些问题摸不清，最好还是用ubuntu或debian   AlmaLinux也可以

**Comment by KKechh** [comment]
ubuntu 也失败了

**Comment by EricJim08** [comment]
点击重新下载，直到可以为止
