### ISSUE TITLE
重安装后无法链接，请求更新

### ISSUE THREAD

**Issue by makailin** [proxysu/ProxySU#226]
重装后发现所有软件安装的服务器均无法链接，无论哪种协议。尝试更换端口，更换服务器，包括购买新域名进行解析，在网络各方面链接正常的情况下均出现不同错误。尝试手动配置服务器就完全没问题。可能因为核心更新？

**Comment by next-autumn** [comment]
更新版本 v4.1.5 

 可能是配置文件中出现空的UUID导致核心启动失败。
