### ISSUE TITLE
检测域名有BUG

### ISSUE THREAD

**Issue by kongbai39** [proxysu/ProxySU#227]
ping "XXXXXXX" -c 1 | sed '1{s/[^(]*(//;s/).*//;q}'
2001:19f0:5401:1ae1:5400:3ff:fed8:7759 (2001:19f0:5401:1ae1:5400:3ff:fed8:7759
本机IP(2001:19f0:5:122d:5400:3ff:fed8:7b18)

**Comment by kongbai39** [comment]
明明ip一样的,他每次都说我的域名和ip不一致,然后安装失败,安装xray和v2ray不会出现这样的问题,trojan和naive都会这样

**Comment by next-autumn** [comment]
是否开启了CDN代理？如果是要先关闭CDN代理。

**Comment by kongbai39** [comment]
没开,只有trojan和naive会出现这样的错误,而且Log显示的ip也是一致的,他却说不一致

**Comment by next-autumn** [comment]
fixed 4.1.5
