### ISSUE TITLE
v4.1.5安装后无法科学上网

### ISSUE THREAD

**Issue by Montel46yfdhbd** [proxysu/ProxySU#229]
如题，系统版本centos8/debian10，运行v4.1.5版本，提示成功。配置为mkcp+dtls，未勾选上传证书，未上传任何证书。另换其它脚本，如233脚本，同样配置，可正常科学上网。困惑中。。错误提示如下：

>  [Warning] [727874073] proxy/http: failed to read response from detectportal.firefox.com > io: read/write on closed pipe
 [Warning] [727874073] app/proxyman/inbound: connection ends > proxy/http: connection ends > proxy/http: failed to write response > write tcp 127.0.0.1:10809->127.0.0.1:50368: wsasend: An established connection was aborted by the software in your host machine.

 127.0.0.1:50393 accepted //edge.microsoft.com:443 [proxy]
 127.0.0.1:50394 accepted http:// edge.microsoft.com/captiveportal/generate_204 [proxy]
``

**Comment by Montel46yfdhbd** [comment]
可能是服务器端有点问题，但完全一样的配置233脚本可以，贴一下错误代码，怎么修改服务器设置？

> ● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/v2ray.service.d
           └─10-donot_touch_single_conf.conf
   Active: failed (Result: exit-code) since Fri 03:20:17 UTC; 9min ago
     Docs: https://www.v2fly.org/
 Main PID: 2071 (code=exited, status=23)
03:20:16 centos8 systemd[1]: Started V2Ray Service.
03:20:16 centos8 v2ray[2071]: V2Ray 4.44.0 (V2Fly, a community-driven edition of V2Ray.) Cu>
03:20:16 centos8 v2ray[2071]: A unified platform for anti-censorship.
03:20:16 centos8 v2ray[2071]:       03:20:16 [Info] main/jsonem: Reading config: /usr/>
03:20:17 centos8 v2ray[2071]: main: failed to read config files: [/usr/local/etc/v2ray/conf>
03:20:17 centos8 systemd[1]: v2ray.service: Main process exited, code=exited, status=23/n/a
03:20:17 centos8 systemd[1]: v2ray.service: Failed with result 'exit-code'.``

**Comment by Montel46yfdhbd** [comment]
用proxysu，同一家云服务器厂商，切换centos\debian\ubuntu，都是同样的问题。求解，困惑的是其它脚本为什么可以？

**Comment by Montel46yfdhbd** [comment]
更新了错误代码，上次没有贴出tls错误的内容。申请证书一直失败，TLS不是必须的吧?看内容是没有TLS证书的问题吗？
安装log最后两条：

> 安装成功

安装成功，请上传您的 TLS 证书。

>

**Comment by Montel46yfdhbd** [comment]
如果是TLS的问题，请问怎么解决呢？

**Comment by next-autumn** [comment]
申请证书需要   服务器开放80端口  域名申请过多需要换二级域名
