### ISSUE TITLE
使用AWS的VPS在UBUNTU下无法以ROOT管理员登录，请问要怎么解决？

### ISSUE THREAD

**Issue by koyehe** [proxysu/ProxySU#233]
在AWS的VPS下使用SSH连接成功后，需要先输入su root才能开启管理员登录，使用ProxySU可以连接到服务器，但一直出现没有管理员权限的提示。是不是ProxySU没有在连接后加入su root的指令？

**Comment by next-autumn** [comment]
su root 在安装过程中也会有一些问题。

可以试试  操作  -> 启用Root账户  创建一个root账户
