### ISSUE TITLE
节点断流，持续大概一到三分钟，频率一天七八次

### ISSUE THREAD

**Issue by shuishiba1997** [proxysu/ProxySU#235]

**Comment by zanzhz1101** [comment]
跟这个项目没关系

**Comment by MisCusi2023** [comment]
ProxySU安装代理，都是采用相应代理官方的安装脚本与方法。只能安装成功，并运行成功，ProxySU即完成任务，在使用中出现的问题，可以去相应的代理项目下发issues，可能会得到更加专业的加回复。
