### ISSUE TITLE
ProxySU安装时出现错误域名未能正确解析到当前VPS的IP上!安装失败！

### ISSUE THREAD

**Issue by zhouyinglong** [proxysu/ProxySU#239]
正在登录远程主机......
主机登录成功!
uname -a
Linux vultr 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装v2ray......
if [[ -f /usr/local/bin/v2ray ]];then echo '1';else echo '0'; fi
0

检测结果：未安装v2ray
检测系统是否符合安装要求......
command -v apt-get
/usr/bin/apt-get

command -v dnf

command -v yum

command -v systemctl
/usr/bin/systemctl

command -v getenforce

检测结果：OK!
apt-get update
Hit:1 http://security.debian.org bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Reading package lists...

apt-get -y install xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version (5.2.5-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

正在检测是否为纯ipv6主机......
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

curl -s https://api.ip.sb/ip --ipv6 --max-time 8
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

检测端口占用情况......
lsof -n -P -i :80 | grep LISTEN

lsof -n -P -i :443 | grep LISTEN

检测结果：未被占用！
开启防火墙相应端口......
ufw allow 80/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)

ufw allow 80/udp
Skipping adding existing rule
Skipping adding existing rule (v6)

ufw allow 443/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)

ufw allow 443/udp
Skipping adding existing rule
Skipping adding existing rule (v6)

yes | ufw reload
Firewall reloaded

校对时间......
时间差符合要求，OK!
正在检测域名是否解析到当前VPS的IP上......
dig @resolver1.opendns.com A www.liyanrufreedom.xyz +short -4 | grep  -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -n 1
95.179.227.137

域名未能正确解析到当前VPS的IP上!安装失败！
发生错误，安装中断......

**Comment by zhouyinglong** [comment]
![微信图片_20220411151502](https://user-images.githubusercontent.com/103411795/162687918-c962b9dd-c7bf-4e79-900b-fea59eba1b2f.png)

**Comment by zhouyinglong** [comment]
测试可以ping通，服务器已经换了好几个了，但是域名只是修改了二级域名但是到这一步均失败

**Comment by zhouyinglong** [comment]
ping可以ping通，服务器换了好几个，二级域名也换了几个，但都到这一步后失败

**Comment by zhouyinglong** [comment]
后续换了个ProxySU版本就可以了

**Comment by captainnx** [comment]
换版本也没用把。。。是ip.sb的问题

**Comment by captainnx** [comment]
把源码里的https://api.ip.sb 替换成http://api.ip.sb

**Comment by Chl-shudou** [comment]
我也遇到同样的问题

**Comment by next-autumn** [comment]
v2.5.7
v4.1.6

fixed
