### ISSUE TITLE
域名地址与ip不匹配

### ISSUE THREAD

**Issue by ohspecial** [proxysu/ProxySU#249]
能链接到vps上，但是在安装Trojan-go时，到解析ip地址的时候就会报这个错误，本地ping域名的ip是对的，使用其他一键脚本也能正常解析，但是只有使用该软件时出错，不知道什么问题

**Comment by ohspecial** [comment]
下载新版本已解决上述问题

**Comment by MisCusi2023** [comment]
试一下最新版，是否还有这一问题？
