### ISSUE TITLE
为什么无法访问8080端口？

### ISSUE THREAD

**Issue by anylones** [proxysu/ProxySU#250]
使用软件搭建xary后，选择安装了vless,vmess,trorjan,ss，选择了手动上传网站。此时运行正常，也能访问网站看到上传的网站。
但此时，我继续搭建Qbittorrent&Filebrowse用于离线下载和取回文件，通过上面使用的网址+8080（Qbittorrent端口）却无法正常访问Qbittorrent管理页面，而是直接访问上传的网站。网址+Filebrowse端口也是访问的网站首页。
之前用的其他脚本，没有出现这个问题。请问一下这个如何解决？

**Comment by next-autumn** [comment]
需要在caddy服务器配置端口，最好是换一下二级域名，和代理域名分开。
