### ISSUE TITLE
Xcore更新不到最新版

### ISSUE THREAD

**Issue by lgfyxx1** [proxysu/ProxySU#297]
升级内核显示的最新版Xcore是1.5.5， 实际已经1.5.8了，可以更新下吗？

谢谢

**Comment by lgfyxx1** [comment]
bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
info: No new version. The current version of Xray is v1.5.5 .
systemctl restart xray

**Comment by wekingchen** [comment]
因为最新的1.5.9还是Pre-release版，Latest版本还是1.5.5
