### ISSUE TITLE
使用“更新配置”功能可能导致服务器断网

### ISSUE THREAD

**Issue by zi-jing** [proxysu/ProxySU#299]
运行环境：Ubuntu 20.04 LTS x64
在已经正常安装服务的机器上使用“更新配置”功能后，有很大概率在配置防火墙的阶段突然断开连接且无法再次连接。
使用VNC连接服务器查看，发现服务器完全无法连接网络，提示“Temporary failure in name resolution”

该问题在多个纯净环境下反复重现，建议尽快修复。

**Comment by next-autumn** [comment]
可能与vps商家os有关，需要手动配置DNS。
