### ISSUE TITLE
brook可以考虑添加到软件中

### ISSUE THREAD

**Issue by Alvin9999** [proxysu/ProxySU#31]
https://github.com/txthinking/brook

**Comment by proxysu** [comment]
这个软件，你用过吗？好用不？我使用过程中，发现有被断流的现象。在使用一段时间后，端口被封。

**Comment by Alvin9999** [comment]
月初被封过1次端口，之后还是比较稳定。

**Comment by proxysu** [comment]
好的，可能不同地区，也有差异，有时间，我会增加这个软件，不过，目前事情有点，业余时间不够。还不知道什么时候才有空。

**Comment by nethawkhu** [comment]
brook常常被封。
