### ISSUE TITLE
希望尽快加入uTLS

### ISSUE THREAD

**Issue by mokiii** [proxysu/ProxySU#310]
介于最近大量被识别的情势。。。。。

**Comment by XgHao** [comment]
部署完 手动添加就行了
编辑 /usr/local/etc/xray/config.json
```json
"xtlsSettings": {
          "allowInsecure": false,
          "fingerprint": "randomized",   // 添加这一行
          "minVersion": "1.2",
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/xray/ssl/xray_ssl.crt",
              "keyFile": "/usr/local/etc/xray/ssl/xray_ssl.key"
            }
          ]
        }
```

**Comment by XgHao** [comment]
有需要可以先在这里下载：https://github.com/XgHao/ProxySU/releases/tag/v4.1.7

PR已提交

**Comment by mokiii** [comment]
> 有需要可以先在这里下载：https://github.com/XgHao/ProxySU/releases/tag/v4.1.7
> 
> PR已提交

感谢

**Comment by ajmz** [comment]
> 有需要可以先在这里下载：https://github.com/XgHao/ProxySU/releases/tag/v4.1.7
> 
> PR已提交

请问是需要Xray-core v1.6.3吧？能否在proxysu的更新内核里面添加支持pre-release，谢谢。

**Comment by XgHao** [comment]
> > 有需要可以先在这里下载：https://github.com/XgHao/ProxySU/releases/tag/v4.1.7
> > PR已提交
> 
> 请问是需要Xray-core v1.6.3吧？能否在proxysu的更新内核里面添加支持pre-release，谢谢。

加上了
有需要前往 https://github.com/XgHao/ProxySU/releases/tag/v4.2.0 下载

**Comment by ajmz** [comment]
> > > 有需要可以先在这里下载：https://github.com/XgHao/ProxySU/releases/tag/v4.1.7
> > > PR已提交
> > 
> > 
> > 请问是需要Xray-core v1.6.3吧？能否在proxysu的更新内核里面添加支持pre-release，谢谢。
> 
> 加上了 有需要前往 https://github.com/XgHao/ProxySU/releases/tag/v4.2.0 下载

强。我用的clash.meta的正式版还不支持uTLS，如果ProxySU能加上xray转clash节点配置功能就更好了。：）
