### ISSUE TITLE
盼修复 谢谢

### ISSUE THREAD

**Issue by boy516** [proxysu/ProxySU#317]
正在登录远程主机......
主机登录成功!
uname -a
Linux AIBOY 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装ss-server......
if [[ -f /usr/local/bin/ss-server ]];then echo '1';else echo '0'; fi
0

检测结果：未安装ss-server
检测系统是否符合安装要求......
command -v apt-get
/usr/bin/apt-get

command -v dnf

command -v yum

command -v systemctl
/bin/systemctl

command -v getenforce

检测结果：OK!
apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists...

apt-get -y install xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version (5.2.2-1.3ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 244 not upgraded.

正在检测是否为纯ipv6主机......
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

curl -s https://api.ip.sb/ip --ipv6 --max-time 8

检测端口占用情况......
lsof -n -P -i :32863 | grep LISTEN

检测结果：未被占用！
开启防火墙相应端口......
ufw allow 32863/tcp
Skipping adding existing rule
Skipping adding existing rule (v6)

ufw allow 32863/udp
Skipping adding existing rule
Skipping adding existing rule (v6)

yes | ufw reload
Firewall not enabled (skipping reload)

系统环境检测完毕，符合安装要求,开始布署......
正在安装SS，使用编译方式，时间稍长，请耐心等待......
curl -o /tmp/tmp.DtDRflVXGX.sh https://raw.githubusercontent.com/proxysu/shellscript/master/ss/ss-install.sh

if [[ -f /tmp/tmp.DtDRflVXGX.sh ]];then echo '1';else echo '0'; fi
1

yes | bash /tmp/tmp.DtDRflVXGX.sh
编译中,请耐心等待.............
[[0;32mInfo[0m] Latest version: [0;32mshadowsocks-libev-3.3.5[0m

244 packages can be upgraded. Run 'apt list --upgradable' to see them.
[[0;32mInfo[0m] shadowsocks-libev-3.3.5.tar.gz [found]
[[0;32mInfo[0m] libsodium-1.0.18.tar.gz [found]
[[0;32mInfo[0m] mbedtls-2.16.6-apache.tgz [found]
[[0;32mInfo[0m] libsodium-1.0.18 already installed.

rm -f /tmp/tmp.DtDRflVXGX.sh

if [[ -f /usr/local/bin/ss-server ]];then echo '1';else echo '0'; fi
0

安装失败,脚本运行出错！
发生错误，安装中断......

**Comment by MisCusi2023** [comment]
看这个提示，应该是在编译ss-server时，出现了错误，没能编译成功。这是老版本的安装方式了，新版本的ss安装是使用xray或者v2ray中的ss协议，客户端是兼容的。可以使用新版本安装试一下。
