### ISSUE TITLE
申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

### ISSUE THREAD

**Issue by martincccc1992** [proxysu/ProxySU#318]
安装证书
安装Acme软件
apt install -y socat
Reading package lists...
Building dependency tree...
Reading state information...
socat is already the newest version (1.7.3.2-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
apt install -y automake autoconf libtool
Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.16.1-4).
libtool is already the newest version (2.4.6-9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
curl  https://get.acme.sh yes | sh
[Sun 30 Oct 2022 04:50:04 PM UTC] Installing from online archive.
[Sun 30 Oct 2022 04:50:04 PM UTC] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Sun 30 Oct 2022 04:50:05 PM UTC] Extracting master.tar.gz
[Sun 30 Oct 2022 04:50:05 PM UTC] Installing to /root/.acme.sh
[Sun 30 Oct 2022 04:50:05 PM UTC] Installed to /root/.acme.sh/acme.sh
[Sun 30 Oct 2022 04:50:05 PM UTC] Installing alias to '/root/.bashrc'
[Sun 30 Oct 2022 04:50:05 PM UTC] OK, Close and reopen your terminal to start using acme.sh
[Sun 30 Oct 2022 04:50:05 PM UTC] Installing cron job
1 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Sun 30 Oct 2022 04:50:05 PM UTC] Good, bash is found, so change the shebang to use bash as preferred.
[Sun 30 Oct 2022 04:50:06 PM UTC] OK
[Sun 30 Oct 2022 04:50:06 PM UTC] Install success!
alias acme.sh=~/.acme.sh/acme.sh

正在申请证书
/root/.acme.sh/acme.sh --force --debug --issue  --standalone  -d   --pre-hook "systemctl stop caddy"  --post-hook  "systemctl start caddy" --server letsencrypt

申请证书失败，如果申请次数过多请更换二级域名，或联系开发者！

**Comment by martincccc1992** [comment]
第一次使用出现如下提示。。。求指点

**Comment by resonanceaoi** [comment]
遇到了相同的情况，换了两个域名都卡在证书这一步

**Comment by next-autumn** [comment]
什么系统及版本？

**Comment by shawchuh** [comment]
刚使用v.4.1.6有同样问题

升级为最新v.4.1.7解决
