### ISSUE TITLE
新增流控和版本的选择功能

### ISSUE THREAD

**Issue by XgHao** [proxysu/ProxySU#320]
有需要的朋友 可以在这里下载
https://github.com/XgHao/ProxySU/releases/tag/v4.2.0

因为自己只用 vless+tcp+xtls的这个选项，所以其他的并没有测试
按需所取

**Comment by TianYaDY** [comment]
大佬！！

**Comment by TianYaDY** [comment]
大佬，可以说说，naive节点安装的问题，应该怎么解决么？
https://github.com/proxysu/ProxySU/issues/305

**Comment by next-autumn** [comment]
> 有需要的朋友 可以在这里下载 https://github.com/XgHao/ProxySU/releases/tag/v4.2.0
> 
> 因为自己只用 vless+tcp+xtls的这个选项，所以其他的并没有测试 按需所取

您有兴趣一起维护吗？
需要保证网络安全，不能用真实github身份、IP...
