### ISSUE TITLE
希望可以添加对X2RAY新流控的支持

### ISSUE THREAD

**Issue by TonyInTokyo** [proxysu/ProxySU#341]
"flow": "xtls-rprx-vision"

**Comment by viremia** [comment]
目前，除xtls-rprx-vision之外的已经弃用了
![image](https://user-images.githubusercontent.com/8912441/211316375-9ce12507-494f-4eb5-b2e3-37458f88f2b4.png)

**Comment by XgHao** [comment]
https://github.com/XgHao/ProxySU/releases/tag/v4.2.0
之前自己用 加了流控和版本选择

**Comment by MisCusi2023** [comment]
已添加，新版本：v4.1.10+同时兼容xtls与普通tls.
