### ISSUE TITLE
V2ray-Core安装失败，请联系开发者

### ISSUE THREAD

**Issue by xiao-github** [proxysu/ProxySU#346]
[https://i.postimg.cc/wBm9hvzt/20230116080708.png](url) 新的几个版本都显示V2ray-Core安装失败， 有人能帮看下是什么问题么？

**Comment by wakedream** [comment]
我也出现了这种情况，。：
6. 安装V2ray-Core
开始安装V2ray-Core
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
info: Installing V2Ray v5.2.1 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-64.zip
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v5.2.1/v2ray-linux-64.zip.dgst
error: Check failed! Please check your network or try again.
removed: /tmp/tmp.mRsOfokVwG
if [[ -f /usr/local/bin/v2ray ]];then echo '1';else echo '0'; fi
0
V2ray-Core安装失败，请联系开发者

**Comment by xiao-github** [comment]
看了v2fly那边  https://github.com/v2fly/fhs-install-v2ray/issues/261
应该是这个问题了
