### ISSUE TITLE
V.2.5.6 SS+TLS+WEBSOCKET+CADDY脚本出错

### ISSUE THREAD

**Issue by kemjjf1** [proxysu/ProxySU#351]
![OW1%4Y83O@R LM~Y)8UAV~U](https://user-images.githubusercontent.com/126338303/221363228-1b8dfb43-0b7c-442d-810c-6fcff00aa8ef.png)

**Comment by MisCusi2023** [comment]
这是旧版本的安装ss方式，使用编译方式，容易出现错误，新版本已经改进，使用xray或者v2ray中的ss协议安装。成功率很高，请下载最新版本。
