### ISSUE TITLE
script err (any methods)

### ISSUE THREAD

**Issue by codthing** [proxysu/ProxySU#352]
正在登录远程主机......
主机登录成功!
uname -a
Linux vultr 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装ss-server......
if [[ -f /usr/local/bin/ss-server ]];then echo '1';else echo '0'; fi
0

检测结果：未安装ss-server
检测系统是否符合安装要求......
command -v apt-get
/usr/bin/apt-get

command -v dnf

command -v yum

command -v systemctl
/usr/bin/systemctl

command -v getenforce

检测结果：OK!
apt-get update
Hit:1 https://apprepo.vultr.com/debian universal InRelease
Hit:2 https://deb.debian.org/debian bullseye InRelease
Hit:3 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:4 https://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...

apt-get -y install xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version (5.2.5-2.1~deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

正在检测是否为纯ipv6主机......
curl -4 ip.sb
199.602.362.524

curl -6 ip.sb
2001:19f0:ac01:b08:4420:3ff:fefe:ae47

检测端口占用情况......
lsof -n -P -i :47712 | grep LISTEN

检测结果：未被占用！
开启防火墙相应端口......
ufw allow 47712/tcp
Rule added
Rule added (v6)

ufw allow 47712/udp
Rule added
Rule added (v6)

yes | ufw reload
Firewall reloaded

系统环境检测完毕，符合安装要求,开始布署......
正在安装SS，使用编译方式，时间稍长，请耐心等待......
curl -o /tmp/tmp.ZCCA6NbZhS.sh https://raw.githubusercontent.com/proxysu/shellscript/master/ss/ss-install.sh

if [[ -f /tmp/tmp.ZCCA6NbZhS.sh ]];then echo '1';else echo '0'; fi
1

yes | bash /tmp/tmp.ZCCA6NbZhS.sh
编译中,请耐心等待.............
[[0;32mInfo[0m] Latest version: [0;32mshadowsocks-libev-3.3.5[0m

All packages are up to date.
[[0;32mInfo[0m] shadowsocks-libev-3.3.5.tar.gz [found]
[[0;32mInfo[0m] libsodium-1.0.18.tar.gz [found]
[[0;32mInfo[0m] mbedtls-2.16.6-apache.tgz [found]
[[0;32mInfo[0m] libsodium-1.0.18 already installed.

rm -f /tmp/tmp.ZCCA6NbZhS.sh

if [[ -f /usr/local/bin/ss-server ]];then echo '1';else echo '0'; fi
0

> version 2.5.6

**Comment by MisCusi2023** [comment]
这是旧版本的安装ss方式，使用编译方式，容易出现错误，新版本已经改进，使用xray或者v2ray中的ss协议安装。成功率很高，请下载最新版本。
