### ISSUE TITLE
SS kcptun plugin installation error

### ISSUE THREAD

**Issue by Deckard-f-Cain** [proxysu/ProxySU#355]
正在登录远程主机......
主机登录成功!
uname -a
Linux localhost.localdomain 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

sed -i 's/echo/#echo/g' ~/.bashrc

sed -i 's/echo/#echo/g' ~/.profile

检测是否运行在root权限下...
id -u
0

检测结果：OK！
检测系统是否已经安装ss-server......
if [[ -f /usr/local/bin/ss-server ]];then echo '1';else echo '0'; fi
0

检测结果：未安装ss-server
检测系统是否符合安装要求......
command -v apt-get
/usr/bin/apt-get

command -v dnf

command -v yum

command -v systemctl
/usr/bin/systemctl

command -v getenforce

检测结果：OK!
apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8,183 kB]
Get:5 http://download.zerotier.com/debian/bullseye bullseye InRelease [36.9 kB]
Get:6 http://deb.debian.org/debian bullseye/main Translation-en [6,240 kB]
Get:7 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [234 kB]
Get:8 http://deb.debian.org/debian-security bullseye-security/main Translation-en [153 kB]
Get:9 http://deb.debian.org/debian bullseye-updates/main amd64 Packages.diff/Index [16.2 kB]
Get:10 http://deb.debian.org/debian bullseye-updates/main Translation-en.diff/Index [6,117 B]
Get:11 http://deb.debian.org/debian bullseye-updates/main amd64 Packages T-2023-02-20-2009.57-F-2022-10-21-2017.32.pdiff [11.1 kB]
Get:11 http://deb.debian.org/debian bullseye-updates/main amd64 Packages T-2023-02-20-2009.57-F-2022-10-21-2017.32.pdiff [11.1 kB]
Get:12 http://deb.debian.org/debian bullseye-updates/main Translation-en T-2022-10-21-2017.32-F-2022-10-21-2017.32.pdiff [2,494 B]
Get:12 http://deb.debian.org/debian bullseye-updates/main Translation-en T-2022-10-21-2017.32-F-2022-10-21-2017.32.pdiff [2,494 B]
Get:13 http://download.zerotier.com/debian/bullseye bullseye/main amd64 Packages [4,153 B]
Fetched 15.1 MB in 6s (2,482 kB/s)
Reading package lists...

apt-get -y install xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
xz-utils is already the newest version (5.2.5-2.1~deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.

正在检测是否为纯ipv6主机......
curl -s https://api.ip.sb/ip --ipv4 --max-time 8
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

curl -s https://api.ip.sb/ip --ipv6 --max-time 8

检测端口占用情况......
lsof -n -P -i :59418 | grep LISTEN

检测结果：未被占用！
开启防火墙相应端口......
系统环境检测完毕，符合安装要求,开始布署......
正在安装SS，使用编译方式，时间稍长，请耐心等待......
curl -o /tmp/tmp.xgJ8XdbdP4.sh https://raw.githubusercontent.com/proxysu/shellscript/master/ss/ss-install.sh

if [[ -f /tmp/tmp.xgJ8XdbdP4.sh ]];then echo '1';else echo '0'; fi
1

yes | bash /tmp/tmp.xgJ8XdbdP4.sh
编译中,请耐心等待.............
********************[[0;32mInfo[0m] Latest version: [0;32mshadowsocks-libev-3.3.5[0m

92 packages can be upgraded. Run 'apt list --upgradable' to see them.
[[0;32mInfo[0m] shadowsocks-libev-3.3.5.tar.gz [found]
[[0;32mInfo[0m] libsodium-1.0.18.tar.gz [found]
[[0;32mInfo[0m] mbedtls-2.16.6-apache.tgz [found]
[[0;32mInfo[0m] libsodium-1.0.18 already installed.

rm -f /tmp/tmp.xgJ8XdbdP4.sh

if [[ -f /usr/local/bin/ss-server ]];then echo '1';else echo '0'; fi
0

安装失败,脚本运行出错！
发生错误，安装中断......

**Comment by MisCusi2023** [comment]
这是旧版本的安装ss方式，使用编译方式，容易出现错误，新版本已经改进，使用xray或者v2ray中的ss协议安装。成功率很高，请下载最新版本。
