### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by qiqiandfei** [proxysu/ProxySU#356]
部署一切正常，完成后手机端V2rayNg扫码导入Vless提示“TLS handshake timeout”
![c9e05ddbd92cf9f6ec43320f24d259a](https://user-images.githubusercontent.com/31001002/224874645-8bd7a2b5-84fc-4381-bebe-ba2399760471.jpg)

导入软路由SSRP显示连接失败
![image](https://user-images.githubusercontent.com/31001002/224874211-b90e5be4-93a3-425b-b3a9-34736540d7d9.png)

VPS SSH查看443端口回显如下：
![image](https://user-images.githubusercontent.com/31001002/224874024-2cd08bed-9cb2-4e5f-8f17-37dd9f4a8048.png)
没有响应握手包

ProxySU配置如下：
![image](https://user-images.githubusercontent.com/31001002/224874914-2f88bdfa-bf58-4399-bdc6-4c59e417a765.png)

VPS上[/usr/local/etc/xray/config.json]文件如下：
{
  "log": {
    "access": "none",
    "loglevel": "none"
  },
  "dns": {},
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "policy": {},
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "665b200e-51a1-492d-b2af-ef77a47099bf",
            "flow": "xtls-rprx-direct"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 8080
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "allowInsecure": false,
          "minVersion": "1.2",
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/usr/local/etc/xray/ssl/xray_ssl.crt",
              "keyFile": "/usr/local/etc/xray/ssl/xray_ssl.key"
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "transport": {},
  "stats": {},
  "reverse": {}
}

**Comment by qiqiandfei** [comment]
443挂了~大家保重~

**Comment by FantaXI** [comment]
请问443挂了是什么意思？我也出现相同的情况，但用国外测试ip:443能正常访问，请问你最后怎么解决的？

**Comment by qiqiandfei** [comment]
> 请问443挂了是什么意思？我也出现相同的情况，但用国外测试ip:443能正常访问，请问你最后怎么解决的？

443挂了就是443端口被防火墙识别，并封杀了，解决办法是换一个端口。需要注意的是被封杀说明自己没有按照要求设置，导致被防火墙识别，我后来修改了正确的配置并更换了端口，目前还苟活着~
