### ISSUE TITLE
能否只使用TLS1.3或者增加安装选项

### ISSUE THREAD

**Issue by supkrogoth** [proxysu/ProxySU#36]
安装后用SSL Server Test检测伪装网站发现支持TLS1.0 1.1等老旧版本。能否安装后统一强制使用TLS1.3增加安全性。又或者增加安装选项？

**Comment by proxysu** [comment]
是哪个模式的伪装网站？还是全部都是？

**Comment by supkrogoth** [comment]
VLESS TCP TLS WEB和VLESS TCP XTLS WEB模式下安装后都是，其他模式由于没有安装尝试所以不清楚。

**Comment by proxysu** [comment]
我再研究一下这个tls1.3，目前还是很熟悉这个。
