### ISSUE TITLE
能否同时有一个同时搭建几个协议的选项

### ISSUE THREAD

**Issue by cn-404-not-found** [proxysu/ProxySU#38]
比如同时一次安装VMESS、VLESS、Trojan等协议，用的都是443端口，有前置分流的，谢谢

**Comment by Alvin9999** [comment]
不行，1个端口1个协议

**Comment by jinwyp** [comment]
推荐一个脚本 支持 trojan-go trojan v2ray 共存，升级和卸载,自动证书续签.可以修改root和ssh端口 支持WS+CDN https://github.com/jinwyp/one_click_script

**Comment by rvpn** [comment]
Can I install ssr , trojan and v2ray on the same server at the same time but with different port ?

**Comment by Alvin9999** [comment]
> Can I install ssr , trojan and v2ray on the same server at the same time but with different port ?

可以呀。

**Comment by rprx** [comment]
该工具支持 https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER

**Comment by proxysu** [comment]
> 比如同时一次安装VMESS、VLESS、Trojan等协议，用的都是443端口，有前置分流的，谢谢

这个可以实现，Trojan做最前端，因为这个软件不像VMESS VLESS那样灵活。所有非Trojan流量转发到VLESS，再结合这个方案：https://github.com/v2fly/v2ray-examples/tree/master/VLESS-TCP-XTLS-WHATEVER
不过，这样并不能让每种方案得到优化。只能是简单的共存，甚至Trojan还会影响处于后端的V2ray的各个协议。所以没有特别的需要。这种多代理共存方案，并不推荐，目前生态最好的要数V2Ray。

**Comment by next-autumn** [comment]
v3.0.1通过xray回落机制实现了此功能，而且配置简单。欢迎试用
