### ISSUE TITLE
铁子们VPN还能用吗？ 我的昨天突然不好使了

### ISSUE THREAD

**Issue by ChangSZ** [proxysu/ProxySU#381]
vless+tcp+xtls

IP没被禁
域名没被禁（并且尝试更换了不同的域名，一级域名都不一样的那种）

但client始终连不上（之前是好使的，client除了扫码配置外，其余未做任何变更操作）

**Comment by MisCusi2023** [comment]
你使用的是那种流控？
按你所说，似乎是端口被阻断了。
如果没有使用最新的流控  xtls-rprx-vision，更新到最新流控。

**Comment by ChangSZ** [comment]
> 你使用的是那种流控？ 按你所说，似乎是端口被阻断了。 如果没有使用最新的流控 xtls-rprx-vision，更新到最新流控。

![image](https://github.com/proxysu/ProxySU/assets/26893331/83cfb413-24b5-4f71-ab16-22e0220cb45d)

多谢~默认空的，有可能真实这个原因。  不过我换成SSR协议就好啦
