### ISSUE TITLE
建议用WPF的MVVC来做一份

### ISSUE THREAD

**Issue by chacha20** [proxysu/ProxySU#39]
我看了代码做了好多判断，用mvvc来设计一下的话，可以省掉好些代码，而且可读性更好。建议作者这么来做一下，以后更新方便些。
给个赞！

**Comment by proxysu** [comment]
谢谢您的建议，我也只是一个初学者，也是业余时间做的，近期的更新，代码做了大幅优化，把很多重复多的步骤，提出来，成为一个功能函数。你说的这个mvvc我有时间去了解一下。
再一次感觉您的建议。
