### ISSUE TITLE
Xray启动失败，xtls-rprx-vision,none 不支持

### ISSUE THREAD

**Issue by phyzhenli** [proxysu/ProxySU#396]
Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: VLESS clients: "flow" doesn't support "xtls-rprx-vision,none" in this version

根据 `https://github.com/XTLS/Xray-core/issues/2533`，应该去掉none

**Comment by libea18** [comment]
@phyzhenli how could we edit it on script ? i mean in auto installation

**Comment by phyzhenli** [comment]
I didn‘t modify the source code. After auto installation，I delete ‘none’ in the config file and restart xray on the VPS server manually.

**Comment by next-autumn** [comment]
4.1.11
