### ISSUE TITLE
若使用CDN，请先关闭

### ISSUE THREAD

**Issue by arronyxzhang** [proxysu/ProxySU#50]
按照trojan 或者 trojan-go无论哪个模式，都出现错误。
弹出窗口显示：域名未能正确解析到VPS的IP上，若解析设置正确，请等待生效后重试。如果域名使用了CDN，请先关闭。

请问如何关闭CDN？  
我使用的是搬瓦工 Debian10 ，刚刚重装的系统，这个VPS之前使用过v2ray+CDN，请问如何关闭CDN？
我把CDN里的 小黄云 点灰色了，还是没有用呀。
求指点

**Comment by proxysu** [comment]
关闭CDN后，需要等待一段时间，一般是十几分钟，有的要等几个小时。等DNS解析真正恢复到原来的vps主机IP后，就可以正常安装了。

**Comment by Romeo0118** [comment]
我也是遇到了同样的情况，好恶心啊
