### ISSUE TITLE
搬瓦工GIA线路的单核+512MB配置，大概10个人共享，用TCP+TLS好还是XTLS好？

### ISSUE THREAD

**Issue by kobehuanghai** [proxysu/ProxySU#59]
看VLESS的配置介绍，TCP+TLS+WEB适合低配置VPS或多人共享。但XTLS不是说开销更低么？搬瓦工GIA线路的单核+512MB配置，大概10人轻度使用共享，上TLS好还是XTLS好？

**Comment by proxysu** [comment]
单从服务器配置看，这两者区别不是很大。可是随意选择。

**Comment by kobehuanghai** [comment]
> 单从服务器配置看，这两者区别不是很大。可是随意选择。

收到谢谢
