### ISSUE TITLE
dalao，请问mKCP可以套TLS吗？

### ISSUE THREAD

**Issue by kokorobeats** [proxysu/ProxySU#64]

**Comment by proxysu** [comment]
按说，是可以套的，不过这个没有深入研究过。

**Comment by kokorobeats** [comment]
可以麻烦dalao有空时添加吗............

**Comment by proxysu** [comment]
这种用法很少见，你能告诉我这种用法有什么优势吗？

**Comment by kokorobeats** [comment]
优势我想不出有什么优势，但是...................就感觉这样很安全？主要是想到，VLESS本身不带任何加密，那么VLESS的mKCP是不是就约等于裸奔了？加个TLS就安全了呢

**Comment by proxysu** [comment]
加个TLS 确实会更安全，不过，性能会有一定损失。这个我考虑一下，如果有必要的话，我会添加这一功能，
