### ISSUE TITLE
不用Caddy2有自己的证书文件怎么搭建

### ISSUE THREAD

**Issue by hdp521** [proxysu/ProxySU#66]
Caddy2证书时间太短，虽然是自动续签的
我有自己的证书文件，怎么使用rpxysu呢

**Comment by proxysu** [comment]
这个功能目前还不支持。

**Comment by hdp521** [comment]
那希望能生成文件到本地，然后我自己来替换。

**Comment by proxysu** [comment]
你是说将生成的证书下载到本地吗？这个不需要的啊，如果你想替换成自己的证书的话，这个要看你使用的哪种代理模式，目前ProxySU使用acme.sh和Caddy这两种工具生成免费的证书，关于Caddy使用自定义证书，请参考Caddy的官方文档说明，需要设置Caddyfile或者编辑其json文件。替换acme.sh生成的证书，你只需要查找当前所用代理的配置文件，里面有证书路径。直接替换即可。

**Comment by proxysu** [comment]
这个使用自定义证书功能，如果我业余时间充足的话，我会考虑加上。

**Comment by hdp521** [comment]
感谢作者，希望加个添加自定义证书功能
或者工具能生成代理的所有配置文件，然后自己修改上传到vps。

不太喜欢caddy2生成的证书。

**Comment by proxysu** [comment]
看时间情况吧，我尽力。

**Comment by hdp521** [comment]
再次感谢作者！

**Comment by next-autumn** [comment]
v3.0.1可上传自有证书，欢迎试用！
