### ISSUE TITLE
宝塔面板nginx和v2ray的websocket+tls+web协议并存问题。

### ISSUE THREAD

**Issue by wangebcjd** [proxysu/ProxySU#67]
系统:debian9
我用一键安装安装了websocket+tls+web后可以正常使用，安装了宝塔面板后也可以正常使用，但是在宝塔里安装了nginx后发现v2ray不能用了。
是否有一种方法可以让V2ray（ ws+tls+web ）和nginx共存

**Comment by proxysu** [comment]
这个恐怕不行，端口有冲突，80与443只能由一个软件占用。ProxySU使用的是Caddy2。除非让Caddy与nginx运行在不同的端口。

**Comment by wangebcjd** [comment]
我试了一下，proxy安装的websocket+tls+web可以通过修改配置文件以利用宝塔的nginx来转发443端口的请求，已经成功了。

**Comment by proxysu** [comment]
那就好，只要效果一样，caddy和nginx都是可以的。

**Comment by yuquan123888** [comment]
> 我试了一下，proxy安装的websocket+tls+web可以通过修改配置文件以利用宝塔的nginx来转发443端口的请求，已经成功了。

**Comment by yuquan123888** [comment]
> 我试了一下，proxy安装的websocket+tls+web可以通过修改配置文件以利用宝塔的nginx来转发443端口的请求，已经成功了。

怎么解决呢？
