### ISSUE TITLE
搬瓦工各版本系统安装Xray失败

### ISSUE THREAD

**Issue by miner1888** [proxysu/ProxySU#70]
搞了一晚上 各个系统都试了 搬瓦工安装Xray全都失败。
折磨的人要崩溃，作者啥时候能解决这个问题？
![1606424617(1)](https://user-images.githubusercontent.com/72506292/100391313-f8e11080-306d-11eb-941e-45dae7cf820e.png)

**Comment by proxysu** [comment]
下载最新的测试版试试，
应该是修复了这个问题。
https://github.com/proxysu/windows/raw/master/ProxySU/bin/Beta/Beta.zip

**Comment by megaslx** [comment]
我也报错了装到xray这一步错了。相关的日志如下
[Install]
WantedBy=multi-user.target
# In case you have a good reason to do so, duplicate this file in the same directory and make your customizes there.
# Or all changes you made will be lost!  # Refer: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
[Service]
ExecStart=
ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json
~~~~~~~~~~~~~~~~
warning: The systemd version on the current operating system is too low.
warning: Please consider to upgrade the systemd or the operating system.

installed: /usr/local/bin/xray
installed: /usr/local/share/xray/geoip.dat
installed: /usr/local/share/xray/geosite.dat
installed: /usr/local/etc/xray/config.json
installed: /var/log/xray/
installed: /var/log/xray/access.log
installed: /var/log/xray/error.log
installed: /etc/systemd/system/xray.service
installed: /etc/systemd/system/xray@.service
removed: /tmp/tmp.3XUhjlWkxA
info: Xray v1.0.0 is installed.
You may need to execute a command to remove dependent software: apt purge curl unzip
Please execute the command: systemctl enable xray; systemctl start xray

rm -f /tmp/tmp.Ic0pmb1LPJ.sh

if [[ -f /usr/local/bin/xray ]];then echo '1';else echo '0'; fi
0

安装失败,脚本运行出错！
发生错误，安装中断......


我看了一下服务器上没有/usr/local/bin这个目录的

**Comment by proxysu** [comment]
你系统用的是哪个linux版本？

**Comment by proxysu** [comment]
可以尝试切换到debian 9或者debian 10上，使用ProxySU。

**Comment by megaslx** [comment]
> 
> 
> 你系统用的是哪个linux版本？

Ubuntu 18.04
