### ISSUE TITLE
汇报两个设计缺陷

### ISSUE THREAD

**Issue by WROIATE** [proxysu/ProxySU#71]
1. 当域名同时绑定了IPv6和IPv4时，使用的ping检查域名绑定
`ping domain -c1 | grep -oE -m1 "([0-9]{1,3}\.){3}[0-9]{1,3}"`
由于Linux会优先IPv6返回，因此会出现返回IPv4空值的情况，建议改用host命令进行查询，以下为示例
`host domain | grep -o 'address .*' | awk '{print $2}'`
该命令会同时返回IPv4以及IPv6地址

2. 某些VPS主机很干净，甚至没有firewalld，建议安装前做个检查

**Comment by proxysu** [comment]
好的，谢谢建议。

**Comment by proxysu** [comment]
问题1已经修复了，会在下一下正式版中推出，
问题2，在程序中应该是会检测一下，是否安装有防火墙的，不过检测的办法是运行：“command -v ufw”或者"command -v firewall-cmd"。这两个命令，不知道是否会全面而准确。还请建议一下。
