### ISSUE TITLE
搬瓦工centos 6~8均安装失败 卡在上传配置文件 提示sftp错误

### ISSUE THREAD

**Issue by SYDW** [proxysu/ProxySU#72]
搬瓦工centos 6~8均安装失败 卡在上传配置文件 提示sftp错误
只有trojan安装成功

**Comment by proxysu** [comment]
可以暂时先切换到debian10。

**Comment by SYDW** [comment]
> 可以暂时先切换到debian10。

端口修改为22就没问题了
