### ISSUE TITLE
可否增加保存服务器登陆信息的功能

### ISSUE THREAD

**Issue by kobehuanghai** [proxysu/ProxySU#73]
有多台服务器在使用proxysu，很方便。但是无法保存登陆信息每次切换有点麻烦（主要是升级）再次感谢您的贡献

**Comment by proxysu** [comment]
因为涉及密码这种比较敏感的信息，一直不想做这个功能。最好的还是个人把多台服务器信息自己记录下来。不过，我再看看吧。这个先记在功能开发备用中。

**Comment by huzy0909** [comment]
我也觉得应该填加一个保存登录信息的功能，我就两个VPS，每次都需要复制密码、ip地址，虽然填的信息不多，但填加后会更方便使用，感谢提供这么好用的软件！！

**Comment by s0trcwd7** [comment]
保存使用过登录信息好啊，现在app基本都保存登录信息吧，我们可以输入密码或密钥登录，支付宝，淘宝，百度网盘，招行银行app,,,,,,电脑端也是啊，登录时输入密码，密钥. 

卸载后也保存啊，IP框，域名，证书备份到你指定目录，上次使用的uuid，上次用proxysu安装的选择等，也可以恢复默认。我们在电脑手机客户端不用改什么，直接使用。争取安装一次后卸载，再次安装时，不用键盘输入任何信息(登录密码或密钥除外)，直接用鼠标操作，

使用的是vps centos7 系统,，v2.5.4版本　使用密码登录安装，使用，卸载都正常。但使用没设置密码密钥登正常，使用加密的密钥，没弹出输入密钥密码框，几秒后就退出了，多次都是这样。不知道什么原因，使用xshell,　winscp, 设置密码的密钥登录正常。vps不太可能重置或更换系统，上面安装一些软件，挂载了硬盘，rclone了 google drive, one drive.等

脚本有些麻烦，proxysu比脚本给我们带来很大方便-:)

**Comment by next-autumn** [comment]
请试用  v3.0.1
