### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by asterriya** [proxysu/ProxySU#75]
info: Installing Xray v1.0.0 for x86_64
Downloading Xray archive: https://github.com/XTLS/Xray-core/releases/download/v1.0.0/Xray-linux-64.zip
error: Download failed! Please check your network or try again.
removed: /tmp/tmp.x0Z40NL1QJ

The same with other stuff like v2ray, trojan-go etc

Only SSR working fine

**Comment by proxysu** [comment]
这个问题的出现，与当前vps的网络有关系，可以试着切换一下linux的版本，换成debian10，再试试。另外如果是纯ipv6的主机，可能还是会有点问题，不推荐使用纯ipv6的主机。

**Comment by asterriya** [comment]
1) I dont have ipv6 and there is only ipv4
2) I'm on Debian9 already, even try to use ubuntu 18.04
3) Previously it's worked well but now it doesnt

**Comment by proxysu** [comment]
ProxySU安装Xray是调用的其官方安装脚本：
bash <(curl -L https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh)

**Comment by asterriya** [comment]
I will try again later and let you know

**Comment by huzy0909** [comment]
可以试着用一下代理安装下，我在安装RACK的VPS时，安装多次，重新安装系统也不行，最后在ProxSU用代理顺利安装，安装速度都快了很多。
