### ISSUE TITLE
PR_END_OF_FILE_ERROR，怎破？

### ISSUE THREAD

**Issue by louisir** [proxysu/ProxySU#77]
部署的trojan，安卓和openwrt上访问正常，pc上访问google和youtube正常，twitter和facebook出现PR_END_OF_FILE_ERROR错误

Secure Connection Failed

An error occurred during a connection to facebook.com. PR_END_OF_FILE_ERROR

请问怎么破？

**Comment by proxysu** [comment]
这个你可能需要到trojan的项目下发问，因为安装错误的话，安卓和openwrt上无法使用的。能使用，表示，安装过程没有出错误。
在pc上出现这种错误，一个可能是trojan程序的原因，
还有一个原因，就是你使用的界面程序的原因。
你是使用trojan的官方客户端，还是其他一些界面客户端。

**Comment by louisir** [comment]
官方客户端1.16

**Comment by louisir** [comment]
我好像解决了。可能是服务器时间和本地时间不一致导致的。我在服务器上把UTC时间修改成CTS时间，修改时区到Asia/Shanghai，手动修改系统时间跟客户端一致（NTP synchronized始终为no，怎么弄都弄不好）。上述一顿折腾后，目前正常了。。。

btw，请教一下大神，NTP synchronized为什么无法同步，我已经在timesyncd.conf中添加了好多ntp服务器，各大学阿里云和国家授时中心的服务器我都添加了，但是systemd-timesyncd还是超时（所以无奈之下我才手动改了系统时间）。

Dec 07 01:00:31 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 202.120.127.191:1
Dec 07 01:00:41 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 101.6.6.172:123 (
Dec 07 01:00:51 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 162.159.200.123:1
Dec 07 01:01:02 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 162.159.200.1:123
Dec 07 01:01:12 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 185.209.85.222:12
Dec 07 01:01:22 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 5.79.108.34:123 (
Dec 07 01:01:32 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 193.182.111.142:1
Dec 07 01:01:43 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 185.255.55.20:123
Dec 07 01:01:53 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 144.76.76.107:123
Dec 07 01:02:03 racknerd-fb299c systemd-timesyncd[8863]: Timed out waiting for reply from 94.130.49.186:123

**Comment by proxysu** [comment]
可能与vps所在的母机环境也有关系。这个我也不是很懂。
