### ISSUE TITLE
建议添加非 root 用户自动运行 sudo -i 功能

### ISSUE THREAD

**Issue by cywy** [proxysu/ProxySU#81]
谷歌云平台，密钥登录为非 root 用户，建议在”检测是否运行在 root 权限"后为非 root用户自动执行 sudo -i 代码。

**Comment by wangebcjd** [comment]
应该怎么用，我的亚马逊也是这样说我没有root权限安装不了

**Comment by proxysu** [comment]
谷歌云可以开通root账户及密码登录。方法：
https://github.com/proxysu/ProxySU/wiki/%E8%B0%B7%E6%AD%8C%E4%BA%91%E5%BC%80%E5%90%AFroot%E8%B4%A6%E6%88%B7%E4%B8%8E%E5%AF%86%E7%A0%81%E7%99%BB%E5%BD%95

亚马逊的应该与谷歌云，差不多，以上方法应该是通用的。
另外可以使用ProxySU工具自带的：系统工具---->启用root密码登录。

**Comment by hunsui** [comment]
V3版本没看到系统工具这个选项呢？

**Comment by next-autumn** [comment]
v4.0.4   【操作】-【启用Root账户】
