### ISSUE TITLE
request

### ISSUE THREAD

**Issue by deyangyvtian** [proxysu/ProxySU#84]
能否将申请证书加到系统工具中
可以单独只申请证书，输出证书路径
如果已有证书，则更新，并显示路径

**Comment by proxysu** [comment]
我先记下来，如果有时间，我会试着添加上。

**Comment by s0trcwd7** [comment]
头几次安装卸载都正常，再安装卡在证书处，退出了。换域名使用正常，呵呵，不想换域名啊,,,
像deyangyvtian 说的那样，同时卸载时不删除证书，安装时有证书检测好些。

**Comment by next-autumn** [comment]
v3.0.1 有单独上传证书功能
