### ISSUE TITLE
希望可以增加一个页面内重新查看配置的功能

### ISSUE THREAD

**Issue by lgfyxx1** [proxysu/ProxySU#85]
当前搭建成功后会保存到本地文件夹。
但是对于好几个电脑换来换去的人来说，有时候正想要看看配置的时候，想起来是家里搭建的~

希望可以加，为大神加鸡腿~~~

**Comment by proxysu** [comment]
嗯，这个可以，就是现在时间不够用。不知道能否有时间添加上。我先记下来吧。

**Comment by lgfyxx1** [comment]
谢谢大神抽时间回复，特别感谢下，这个项目对我我们这种菜鸟来说，真的太好用了！

**Comment by next-autumn** [comment]
欢迎试用测试版v3.0.1
