### ISSUE TITLE
可否將面版中間的 顯示狀態模式 改成 終端命令模式

### ISSUE THREAD

**Issue by pandy003** [proxysu/ProxySU#86]
感謝您提供軟件，提一個建議，將面版中間的 顯示狀態模式 改成 終端命令模式。
顯示狀態模式：可以顯示目前工作狀態
終端命令模式：可以輸入指令並顯示目前工作狀態
謝謝

**Comment by proxysu** [comment]
我明白你的意思，但是这个ProxySU完全要像是其他的ssh的终端那样，没有必要，而且由于内部实现机制的原因，也无法实现。不过，可以添加一个单个指令输入框。在输入框中输入要执行的指令，并执行，回显结果。这个是可以实现的。

**Comment by pandy003** [comment]
謝謝了解
