### ISSUE TITLE
能否增加一个sudo su功能

### ISSUE THREAD

**Issue by dumplingdumpling** [proxysu/ProxySU#87]
在亚马逊云上部署的话,一般是以ubuntu用户登录,所以能不能增加一个判断是否是root用户,如果不是就切换到root用户?

**Comment by proxysu** [comment]
这个是可以实现的，但是以目前来看，需要修改大量的代码。所以，现在没有时间去做这种适配，只能是自己启用root账户。
方法，可以谷歌一下，也可以试着用ProxySU自带的工具：系统工具--->启用root账户密码登录。

**Comment by dumplingdumpling** [comment]
好的，谢谢~
