### ISSUE TITLE
2.5.4安装后访问出错

### ISSUE THREAD

**Issue by cx9208** [proxysu/ProxySU#88]
![QQ截图20201226011402](https://user-images.githubusercontent.com/32755896/103144335-cf95cc00-4762-11eb-9f7c-9e08336638cb.png)

最新版安装后访问网站会提示这个错误，老版可以正常使用

**Comment by proxysu** [comment]
先按着这个里面的常用问题，排除一下，如果实在不行，就可以先用老版的，
另外，安装的是哪个代理模式？使用哪个版本的linux系统？

**Comment by cx9208** [comment]
v2ray的尝鲜模式，debian10。
没所谓了，我先用着老版，等xray出分享链接了转到xray去
