### ISSUE TITLE
多用户可以搞吗。

### ISSUE THREAD

**Issue by mingicemsn** [proxysu/ProxySU#9]
自己架设vps，想v2ray多用户，或者trojan多用户。

**Comment by proxysu** [comment]
这个工具只是供自用的，不适合建机场。如果以后这种需求的人多，我会考虑加入，目前来看感觉用处不是很大。我先加入到备用功能开发计划中。什么时候添加。这个还未确定。

**Comment by eat-peach** [comment]
+1,同期待多用户，特别是naiveproxy

**Comment by kobehuanghai** [comment]
> 这个工具只是供自用的，不适合建机场。如果以后这种需求的人多，我会考虑加入，目前来看感觉用处不是很大。我先加入到备用功能开发计划中。什么时候添加。这个还未确定。

VLESS+TCP+XTLS+WEB 下直接自己修改config.json可以实现多用户吗？刚刚试了下好像不行

**Comment by proxysu** [comment]
可以实现多用户，你需要对v2ray的config.json有一个了解。
https://www.v2fly.org/config/protocols/vless.html#inboundconfigurationobject

    "clients": [
        {
            "id": "27848739-7e62-4138-9fd3-098a63964b6b",
            "flow": "",
            "level": 0,
            "email": "love@v2fly.org"
        },
      {
            "id": "27848739-7e62-4138-9fd3-098a63964dfre",
            "flow": "",
            "level": 0,
            "email": "love@v2fly.org"
        }
    ],

这个就是多用户

**Comment by kobehuanghai** [comment]
> 可以实现多用户，你需要对v2ray的config.json有一个了解。
> https://www.v2fly.org/config/protocols/vless.html#inboundconfigurationobject
> 
> ```
> "clients": [
>     {
>         "id": "27848739-7e62-4138-9fd3-098a63964b6b",
>         "flow": "",
>         "level": 0,
>         "email": "love@v2fly.org"
>     },
>   {
>         "id": "27848739-7e62-4138-9fd3-098a63964dfre",
>         "flow": "",
>         "level": 0,
>         "email": "love@v2fly.org"
>     }
> ],
> ```
> 
> 这个就是多用户

明白收到，我看了下VLESS+TCP+XTLS+WEB默认的流控是xtls-rprx-origin，如果装了最新版的核心，在这块直接改xtls-rprx-direct就行了吧？没有其他地方需要改了吧?

**Comment by proxysu** [comment]
没有了

**Comment by lllrrr2** [comment]
同期待多用户，特别是naiveproxy
