### ISSUE TITLE
证书申请成功，但实际上似乎并没有成功？

### ISSUE THREAD

**Issue by ImagineBook** [proxysu/ProxySU#94]
前几天突然失效了，直接输入域名想看下caddy是否正常，结果caddy页面也出不来，错误信息是SSL_ERROR_UNRECOGNIZED_NAME_ALERT，这个错误好像是SSL证书验证失败才会出现的吧，然后为了验证一下是否是我浏览器的原因，我用了一下第三方的证书验证网站（比如https://www.ssldun.com/tools/ssl-checker.php ），发现我的域名根本没有证书
于是干脆直接重装vps，用proxySU从头安装（尝鲜方案的vless+vmess+trojan+tcp+ws+web），日志显示一切顺利，证书信息也有，但是结果一样，依然检测不到证书，请问是Let's Encrypt的问题还是proxySU的问题还是我的域名被封了？如果是被封了，应该申请失败吧？
我现在使用的是一个三级域名，如果是域名被封了，我再换一个三级域名可以解决吗

**Comment by ImagineBook** [comment]
在服务器上可以找到日志里的crt文件，难道是我每次申请成功后Let's Encrypt立刻取消了我的证书？？？

**Comment by ImagineBook** [comment]
换域名不能解决

**Comment by lgfyxx1** [comment]
换个VPS

**Comment by ImagineBook** [comment]
> 
> 
> 换个VPS

刚重开了一台新vps试了下，依然是SSL_ERROR_UNRECOGNIZED_NAME_ALERT

**Comment by ImagineBook** [comment]
解决了，虽然不确定原因，但感觉好像是Let's Encrypt最近在申请成功后会访问一次域名来了解证书给了什么网站，发现是caddy页面就会被吊销，我以前都不填伪装网址的域名，所以直接浏览器访问会跳到caddy的页面，但是刚才试着填了一下伪装网站（填了微软的必应bing.com）就可以正常连接了，大概是爬虫访问后识别到的是重定向后的bing.com而不是caddy
