### ISSUE TITLE
甲骨文Ubuntu系统acme.sh安装失败

### ISSUE THREAD

**Issue by jhgongfu** [proxysu/ProxySU#98]
日志如下
[193.123._2021-1-31-2-20-20.txt](https://github.com/proxysu/ProxySU/files/5898564/193.123._2021-1-31-2-20-20.txt)

**Comment by xxllllll** [comment]
今天谷歌云debian也acme.sh安装失败

**Comment by strena** [comment]
我现在安装trojango 就提示 acme.sh安装失败   之前我的vps都没有这个问题   其他的像xray 就没问题

**Comment by strena** [comment]
不维护不更新了码

**Comment by hujiao80** [comment]
遇到同样问题，感觉是acme更新，不支持原来的参数了

**Comment by next-autumn** [comment]
正在解决此问题...稍后更新。

**Comment by next-autumn** [comment]
新版本修复了
